export const WHATSAPP_NUMBER = "2348150684208";
export const WHATSAPP_NUMBER_2 = "2347086185912";
export const CONTACT_EMAIL = "oghenevwededavid13@gmail.com";
export const CONTACT_ADDRESS = "28, Alhaji Yusuf, Olodi Apapa, Lagos";
export const BRAND_NAME = "O.V Styles";
export const BRAND_TAGLINE = "Couture";
export const TIKTOK_URL = "https://www.tiktok.com/@o.v.styles";

export const SOCIAL_LINKS = {
  facebook: "https://facebook.com/ovstyles",
  instagram: "https://instagram.com/ovstyles",
  tiktok: "https://www.tiktok.com/@o.v.styles",
};

export const getWhatsAppUrl = (productName: string) =>
  `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(
    `Hello O.V Styles, I'm interested in purchasing: ${productName}. Please provide more details.`
  )}`;

export type Language = "en" | "yo" | "ig" | "ha" | "urh" | "fr" | "ar" | "ru" | "zh" | "hi";

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "yo", label: "Yoruba", flag: "🇳🇬" },
  { code: "ig", label: "Igbo", flag: "🇳🇬" },
  { code: "ha", label: "Hausa", flag: "🇳🇬" },
  { code: "urh", label: "Urhobo", flag: "🇳🇬" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "ar", label: "العربية", flag: "🇸🇦" },
  { code: "ru", label: "Русский", flag: "🇷🇺" },
  { code: "zh", label: "中文", flag: "🇨🇳" },
  { code: "hi", label: "हिन्दी", flag: "🇮🇳" },
];

export const TRANSLATIONS: Record<Language, {
  // Nav
  home: string; about: string; marketplace: string; contact: string;
  // Hero
  exploreCollection: string; bookFitting: string;
  tagline: string; tagline2: string; tagline3: string; tagline4: string; tagline5: string;
  newCollection: string; collection: string; newSeason: string;
  // Featured
  featuredPieces: string; featuredDesc: string;
  shopByCategory: string; viewCollection: string;
  // About section
  ourStory: string; readMore: string;
  aboutHeading: string; aboutP1: string; aboutP2: string;
  yearsLabel: string; designsLabel: string; clientsLabel: string;
  // CEO section
  theVisionary: string; meetDirector: string;
  ceoTitle: string; ceoSubtitle: string;
  mindBehind: string; codeAndCouture: string;
  ceoBio1: string; ceoBio2: string;
  tagHauteCouture: string; tagTechDesign: string; tagAfricanLuxury: string;
  fullStory: string;
  // Values
  whatWeStandFor: string; ourValues: string;
  val1Title: string; val1Desc: string;
  val2Title: string; val2Desc: string;
  val3Title: string; val3Desc: string;
  // Process
  howItWorks: string; bespokeProcess: string;
  step1Title: string; step1Desc: string;
  step2Title: string; step2Desc: string;
  step3Title: string; step3Desc: string;
  step4Title: string; step4Desc: string;
  // Testimonials
  clientLove: string; whatTheySay: string;
  t1Quote: string; t1Name: string; t1Title: string;
  t2Quote: string; t2Name: string; t2Title: string;
  t3Quote: string; t3Name: string; t3Title: string;
  // CTA
  discoverLatest: string; discoverText: string;
  shopNow: string;
  // Newsletter
  newsletterTitle: string; newsletterDesc: string;
  emailPlaceholder: string; subscribe: string;
  // Footer
  quickLinks: string; contactUs: string; followUs: string; allRights: string;
  // About page
  aboutPageHeroSub: string;
  aboutPageEst: string;
  theVision: string;
  craftingElegance: string;
  visionP1: string; visionP2: string;
  philosophyLabel: string; philosophyHeading: string;
  philosophyP1: string; philosophyP2: string;
  founderQuote: string; founderQuoteAttr: string;
  journeyLabel: string; ourMilestones: string;
  m1: string; m2: string; m3: string; m4: string; m5: string; m6: string;
  directorLabel: string; directorHeading: string;
  directorFullBio1: string; directorFullBio2: string; directorFullBio3: string;
  aboutVal1Title: string; aboutVal1Desc: string;
  aboutVal2Title: string; aboutVal2Desc: string;
  aboutVal3Title: string; aboutVal3Desc: string;
  workWithUs: string; createSomething: string; createDesc: string;
  shopCollection: string; getInTouch: string;
  // Contact page
  contactPageHeroSub: string; contactPageEst: string;
  getInTouchHeading: string; getInTouchDesc: string;
  sendMessage: string; messageSent: string; messageSentDesc: string;
  formName: string; formEmail: string; formPhone: string; formSubject: string; formMessage: string;
  formNamePlaceholder: string; formEmailPlaceholder: string; formPhonePlaceholder: string;
  formSubjectPlaceholder: string; formMessagePlaceholder: string;
  formSending: string; formSend: string;
  formSubjectOpt1: string; formSubjectOpt2: string; formSubjectOpt3: string; formSubjectOpt4: string;
  visitUs: string; callUs: string; emailUs: string; hoursLabel: string; hoursValue: string;
  whatsappUs: string; whatsappDesc: string; messageOnWhatsapp: string;
  faqLabel: string; faqHeading: string;
  faq1Q: string; faq1A: string;
  faq2Q: string; faq2A: string;
  faq3Q: string; faq3A: string;
  faq4Q: string; faq4A: string;
  // Shop / Cart
  addToCart: string; addedToCart: string; removeFromCart: string;
  cart: string; cartEmpty: string; cartEmptyDesc: string;
  cartTotal: string; checkoutWhatsapp: string; continueShopping: string;
  qty: string; itemsInCart: string; clearCart: string;
  loved: string; loves: string; itemLoved: string;
  filterAll: string; sortBy: string; sortNewest: string; sortPriceLow: string; sortPriceHigh: string; sortMostLoved: string;
  noItemsFound: string; searchItems: string;
  // Misc
  searchPlaceholder: string; filters: string; clearFilters: string;
  piecesFound: string; category: string; color: string; priceRange: string;
  purchase: string;
}> = {
  en: {
    home: "Home", about: "About", marketplace: "Shop", contact: "Contact",
    exploreCollection: "Explore Collection", bookFitting: "Book a Fitting",
    tagline: "Where Heritage Meets Haute Couture",
    tagline2: "Dressed for Every Unforgettable Moment",
    tagline3: "Crafted to Perfection, Worn with Pride",
    tagline4: "Modern African Style, Redefined",
    tagline5: "Every Stitch Tells a Story",
    newCollection: "New Collection", collection: "Collection", newSeason: "New Season",
    featuredPieces: "Featured Pieces",
    featuredDesc: "Individually selected from our current atelier, each piece a convergence of culture, couture, and contemporary artistry.",
    shopByCategory: "Shop by Category", viewCollection: "View Full Collection",
    ourStory: "Our Story", readMore: "Read More",
    aboutHeading: "About O.V Styles",
    aboutP1: "O.V Styles is a Lagos-based fashion house dedicated to producing garments of enduring elegance, pieces that honour African heritage while commanding global attention. Each design is conceived with intention, executed with discipline, and delivered with pride.",
    aboutP2: "From intimately tailored bespoke commissions to curated ready-to-wear releases, our atelier has become a trusted name among discerning clients across Nigeria and the diaspora, dressing women who refuse to be ordinary.",
    yearsLabel: "Years", designsLabel: "Designs", clientsLabel: "Clients",
    theVisionary: "The Visionary", meetDirector: "Meet the Creative Director",
    ceoTitle: "Creative Director", ceoSubtitle: "O.V Styles · Lagos, Nigeria",
    mindBehind: "The Mind Behind the Brand", codeAndCouture: "Where Code Meets Couture",
    ceoBio1: "The creative force behind O.V Styles is a rare breed, a fashion visionary who is equally at home writing backend architecture as he is sketching a silk silhouette. With deep roots in software engineering and an obsessive eye for garment construction, he approaches fashion the way great engineers approach systems: with logic, precision, and an unrelenting pursuit of perfection.",
    ceoBio2: "His dual mastery allows O.V Styles to operate at the intersection of tradition and technology, where hand-crafted tailoring meets data-driven design intelligence. The result is a label that does not simply follow trends, but architects them.",
    tagHauteCouture: "Haute Couture", tagTechDesign: "Tech-Driven Design", tagAfricanLuxury: "African Luxury",
    fullStory: "Full Story",
    whatWeStandFor: "What We Stand For", ourValues: "Our Values",
    val1Title: "Craftsmanship", val1Desc: "Every garment is hand-finished with surgical precision, where no detail is too small and no standard too high.",
    val2Title: "Heritage", val2Desc: "Rooted in the richness of African textile tradition, each design bridges ancestral artistry with modern sophistication.",
    val3Title: "Exclusivity", val3Desc: "Strictly limited production runs ensure that every client steps out in a piece that is genuinely, unmistakably their own.",
    howItWorks: "How It Works", bespokeProcess: "The Bespoke Process",
    step1Title: "Consultation", step1Desc: "We open with an in-depth conversation, exploring your vision, occasion, and the statement you wish to make.",
    step2Title: "Design", step2Desc: "Our creative team translates your intent into detailed sketches, curating fabric and silhouette proposals tailored to you.",
    step3Title: "Craft", step3Desc: "Master tailors bring each design to life using premium materials, with every seam and finish executed by hand.",
    step4Title: "Delivery", step4Desc: "The completed piece is delivered alongside a final fitting session, ensuring an immaculate, flawless result.",
    clientLove: "Client Love", whatTheySay: "What They Say",
    t1Quote: "O.V Styles dressed me for my wedding and I felt like royalty. The level of craftsmanship is simply unmatched anywhere in Lagos.",
    t1Name: "Amara O.", t1Title: "Bride · Lagos",
    t2Quote: "I have worn international luxury labels, but nothing rivals the personal touch and quality that O.V Styles delivers. It is in a class of its own.",
    t2Name: "Chidinma E.", t2Title: "TV Personality · Abuja",
    t3Quote: "Every piece carries a story. I receive compliments without exception each time I step out in one of their designs.",
    t3Name: "Fatima B.", t3Title: "Entrepreneur · Kano",
    discoverLatest: "Discover the Latest\nCollection",
    discoverText: "Discover exquisite pieces crafted with passion and precision for the modern fashion connoisseur.",
    shopNow: "Shop Now",
    newsletterTitle: "Join the O.V Styles Circle",
    newsletterDesc: "Be the first to know about new collections, exclusive events, and private sales.",
    emailPlaceholder: "Your email address", subscribe: "Subscribe",
    quickLinks: "Quick Links", contactUs: "Contact Us", followUs: "Follow Us",
    allRights: "All rights reserved.",
    searchPlaceholder: "Search by name, type, description...",
    filters: "Filters", clearFilters: "Clear Filters", piecesFound: "pieces found",
    category: "Category", color: "Color", priceRange: "Price Range", purchase: "Purchase",
    aboutPageHeroSub: "Born in Lagos. Worn by the world.",
    aboutPageEst: "Est. 2012",
    theVision: "The Vision", craftingElegance: "Crafting Elegance Since Day One",
    visionP1: "O.V Styles was born from an obsession with precision and a deep reverence for African identity. Every fabric choice, every silhouette, every hand-finished hem exists to serve one purpose: to make the woman wearing it feel genuinely extraordinary.",
    visionP2: "We do not chase trends. We study them, distil what matters, and build garments that will outlast the season they were born in. This is not fast fashion. This is considered craft.",
    philosophyLabel: "Philosophy", philosophyHeading: "Fashion with Purpose",
    philosophyP1: "We believe in sustainable luxury, creating beautiful garments that respect both the artisans who make them and the environment we share. Our commitment to quality over quantity ensures that every O.V Styles piece is built to endure.",
    philosophyP2: "From the sourcing of premium fabrics to the final hand-finished details, our process honours the tradition of haute couture while embracing the tools and intelligence of modern design.",
    founderQuote: "Every garment we create is a love letter to African culture, written in thread and fabric.",
    founderQuoteAttr: "Creative Director, O.V Styles",
    journeyLabel: "Journey", ourMilestones: "Our Milestones",
    m1: "O.V Styles founded in Lagos, Nigeria",
    m2: "First showcase at Lagos Fashion Week",
    m3: "Dressed first celebrity for a major awards ceremony",
    m4: "Expanded reach and began international commissions",
    m5: "Launched curated ready-to-wear collection online",
    m6: "500+ bespoke pieces delivered, 50+ distinguished clients",
    directorLabel: "The Creative Director", directorHeading: "The Architect of O.V Styles",
    directorFullBio1: "The mind behind O.V Styles defies easy categorisation. Equal parts fashion director and software engineer, he brings a systems-thinking rigour to the world of couture that few designers can claim.",
    directorFullBio2: "Trained in garment construction and deeply fluent in backend engineering, he designed O.V Styles not just as a fashion label but as a precision-built creative operation, where every process from client intake to final delivery is engineered for excellence.",
    directorFullBio3: "His vision is simple and uncompromising: African luxury should not be an aspiration. It should be the standard.",
    aboutVal1Title: "Craftsmanship", aboutVal1Desc: "Every piece is meticulously hand-finished by skilled hands that bring decades of experience to each garment.",
    aboutVal2Title: "Elegance", aboutVal2Desc: "Our designs embody timeless elegance, combining classic silhouettes with a contemporary sensibility that never dates.",
    aboutVal3Title: "Heritage", aboutVal3Desc: "We celebrate African heritage through modern design, creating pieces that honour tradition while pointing firmly forward.",
    workWithUs: "Work With Us", createSomething: "Let's Create Something Extraordinary",
    createDesc: "Whether you are commissioning a bespoke piece or exploring the collection, we welcome every conversation.",
    shopCollection: "Shop Collection", getInTouch: "Get in Touch",
    contactPageHeroSub: "We would love to hear from you.", contactPageEst: "Lagos, Nigeria",
    getInTouchHeading: "Get in Touch", getInTouchDesc: "Whether you are commissioning a bespoke piece, attending a fitting, or simply curious about our work, reach out and we will respond within 24 hours.",
    sendMessage: "Send a Message", messageSent: "Message Received",
    messageSentDesc: "Thank you for reaching out. We will be in touch within 24 hours.",
    formName: "Full Name", formEmail: "Email Address", formPhone: "Phone Number",
    formSubject: "Subject", formMessage: "Your Message",
    formNamePlaceholder: "Your full name", formEmailPlaceholder: "your@email.com",
    formPhonePlaceholder: "+234 800 000 0000", formSubjectPlaceholder: "How can we help?",
    formMessagePlaceholder: "Tell us about your occasion, the piece you have in mind, or anything else you would like us to know...",
    formSending: "Sending...", formSend: "Send Message",
    formSubjectOpt1: "Bespoke Commission", formSubjectOpt2: "Book a Fitting",
    formSubjectOpt3: "General Enquiry", formSubjectOpt4: "Partnership / Press",
    visitUs: "Visit the Atelier", callUs: "Call Us", emailUs: "Email Us",
    hoursLabel: "Atelier Hours", hoursValue: "Mon – Sat, 9am – 6pm WAT",
    whatsappUs: "Message on WhatsApp", whatsappDesc: "Prefer a faster reply? Send us a message directly on WhatsApp and we will respond promptly.",
    messageOnWhatsapp: "Open WhatsApp",
    faqLabel: "FAQ", faqHeading: "Common Questions",
    faq1Q: "How long does a bespoke piece take?", faq1A: "Bespoke commissions typically take between 2 to 6 weeks depending on the complexity of the design and fabric availability. We will give you a clear timeline at your consultation.",
    faq2Q: "Do you offer ready-to-wear pieces?", faq2A: "Yes. Our curated ready-to-wear collection is available through the shop. These pieces are produced in strictly limited runs to preserve their exclusivity.",
    faq3Q: "Can I book a fitting before committing?", faq3A: "Absolutely. We encourage an initial consultation so we can understand your vision fully before any commitment is made. Contact us to schedule.",
    faq4Q: "Do you ship internationally?", faq4A: "Yes, we deliver to clients across Nigeria and internationally. Shipping timelines and costs will be confirmed at the time of order.",
    addToCart: "Add to Cart", addedToCart: "Added", removeFromCart: "Remove",
    cart: "Cart", cartEmpty: "Your cart is empty", cartEmptyDesc: "Browse the collection and add pieces you love.",
    cartTotal: "Total", checkoutWhatsapp: "Checkout via WhatsApp", continueShopping: "Continue Shopping",
    qty: "Qty", itemsInCart: "items in cart", clearCart: "Clear Cart",
    loved: "Loved", loves: "loves", itemLoved: "You loved this piece",
    filterAll: "All", sortBy: "Sort by", sortNewest: "Newest", sortPriceLow: "Price: Low to High", sortPriceHigh: "Price: High to Low", sortMostLoved: "Most Loved",
    noItemsFound: "No pieces found", searchItems: "Search pieces...",
  },
  yo: {
    home: "Ile", about: "Nipa Wa", marketplace: "Ile-Itaja", contact: "Kan Si Wa",
    exploreCollection: "Wo Akojopo", bookFitting: "Ṣe Ipinnu",
    tagline: "Ibi Ti Aṣa Pade Igbalode", tagline2: "Ti a Ṣe fun Gbogbo Akoko",
    tagline3: "A Ṣe Pẹlu Ifẹ ati Igberaga", tagline4: "Ara Afrika Ode Oni", tagline5: "Gbogbo Abẹrẹ Sọ Itan",
    newCollection: "Akojopo Tuntun", collection: "Akojopo", newSeason: "Akoko Tuntun",
    featuredPieces: "Awọn Aṣọ Pataki",
    featuredDesc: "Ti a yan lati inu atelier wa lọwọlọwọ — aṣọ kọọkan jẹ apapọ aṣa, couture, ati iṣẹ-ọnà ode oni.",
    shopByCategory: "Ra nipasẹ Ẹka", viewCollection: "Wo Gbogbo Akojopo",
    ourStory: "Itan Wa", readMore: "Ka Siwaju",
    aboutHeading: "Nipa O.V Styles",
    aboutP1: "O.V Styles jẹ ile-aṣọ ni Lagos ti o ṣe igbẹhin si ṣiṣe awọn aṣọ ti o ni ẹwà pipẹ — awọn aṣọ ti o ṣe ola fun ohun-ini Afrika lakoko ti o fa ifojusi agbaye.",
    aboutP2: "Lati awọn aṣọ bespoke titi di awọn akojọpo ready-to-wear, atelier wa ti di orukọ igbẹkẹle laarin awọn alabara ti o mọ daradara kọja Nigeria.",
    yearsLabel: "Ọdún", designsLabel: "Àpèjúwe", clientsLabel: "Àwọn Onibàárà",
    theVisionary: "Olóye", meetDirector: "Pàdé Òṣìṣẹ́ Ìgbékalẹ̀",
    ceoTitle: "Òṣìṣẹ́ Ìgbékalẹ̀", ceoSubtitle: "O.V Styles · Lagos, Nigeria",
    mindBehind: "Ọkàn Lẹ́yìn Àmì", codeAndCouture: "Ibi Ti Kóòdù Pàdé Aṣọ",
    ceoBio1: "Agbára ìgbékalẹ̀ tí ó wà lẹ́yìn O.V Styles jẹ́ ẹni àkànṣe — alájọsọ́ tí ó mọ iṣẹ́-ẹ̀rọ kọmputa àti ṣíṣe aṣọ dọ́gba.",
    ceoBio2: "Ìmọ̀ rẹ̀ méjì gba O.V Styles láàyè láti ṣiṣẹ́ ni ibi tí àṣà ìbílẹ̀ pàdé ìmọ̀-ẹ̀rọ — níbi tí gbígbé aṣọ pàdé ọgbọ́n àpẹrẹ.",
    tagHauteCouture: "Haute Couture", tagTechDesign: "Ìmọ̀-ẹ̀rọ Àpẹrẹ", tagAfricanLuxury: "Ìtàjẹsílẹ̀ Áfríkà",
    fullStory: "Ìtàn Kíkún",
    whatWeStandFor: "Ohun Tí A Dúró Fún", ourValues: "Àwọn Ìdásílẹ̀ Wa",
    val1Title: "Ọgbọ́n-Iṣẹ́", val1Desc: "Aṣọ kọọkan ti pari pẹlu ìdúróṣinṣin — níbi tí kò sí àlàyé tí ó kéré ju.",
    val2Title: "Ohun-Ìní", val2Desc: "Ti gbé ìsìn sí ọrọ̀ àṣà aṣọ Áfríkà, aṣọ kọọkan so ìmọ̀ àti ìgbàlódé pọ̀.",
    val3Title: "Ìyàtọ̀", val3Desc: "Àwọn ṣíṣe tí o ní àgbékalẹ̀ ní dídíwọ́n dájú pé onibàárà kọọkan gba nǹkan àkànṣe.",
    howItWorks: "Bí Ó Ṣe Ń Ṣiṣẹ́", bespokeProcess: "Ìlànà Bespoke",
    step1Title: "Ìfọ̀rọ̀wánilẹ́nuwò", step1Desc: "A bẹ̀rẹ̀ pẹ̀lú ìjíròrò jíjinlẹ̀ — ṣíṣe ìwádìí ìrísí rẹ, àyẹyẹ, àti ọ̀rọ̀ tí o fẹ́ sọ.",
    step2Title: "Àpẹrẹ", step2Desc: "Ẹgbẹ́ ìgbékalẹ̀ wa túmọ̀ ète rẹ sí àwọn àfihàn alálàyé.",
    step3Title: "Iṣẹ́", step3Desc: "Àwọn aṣọ-olóye mú aṣọ kọọkan wá sí ìmúṣẹ pẹ̀lú àwọn ohun èlò didára.",
    step4Title: "Ìfẹsẹ̀wọnsẹ̀", step4Desc: "Aṣọ tí a pari yóò wà pẹ̀lú ìdánwò ikẹyìn — láti ṣe dájú àbájáde tí ó dára.",
    clientLove: "Ifẹ Onibàárà", whatTheySay: "Ohun Tí Wọn Sọ",
    t1Quote: "O.V Styles ṣe aṣọ mi fun ìgbéyàwó mi, mo sì ní ìmọ̀lára bí ọba. Ọgbọ́n-iṣẹ́ ko ni ibamu nibikibi ni Lagos.",
    t1Name: "Amara O.", t1Title: "Ìyàwó · Lagos",
    t2Quote: "Mo ti wọ àwọn àmì ìtàjẹsílẹ̀ àgbáyé, ṣùgbọ́n kò sí ohun tí ó bára dé àkàwé ti O.V Styles.",
    t2Name: "Chidinma E.", t2Title: "Olókìkí TV · Abuja",
    t3Quote: "Aṣọ kọọkan gbe ìtàn. Mo máa ń gba ìyin láìsí àsẹ ni gbogbo ìgbà tí mo bá wọ àpẹrẹ wọn.",
    t3Name: "Fatima B.", t3Title: "Oníṣòwò · Kano",
    discoverLatest: "Ṣàwárí Akojopo Tuntun",
    discoverText: "Ṣàwárí àwọn aṣọ ìyanu tí a ṣe pẹ̀lú ìfẹ́ àti ìdúróṣinṣin.",
    shopNow: "Ra Bayi",
    newsletterTitle: "Darapọ̀ Mọ̀ O.V Styles", newsletterDesc: "Jẹ́ àkọ́kọ́ láti mọ̀ nípa àwọn akojopo tuntun.",
    emailPlaceholder: "Adírẹ́sì ìmẹ́èlì rẹ", subscribe: "Forúkọsílẹ̀",
    quickLinks: "Àwọn Ọ̀nà Kúkúrú", contactUs: "Kan Sí Wa", followUs: "Tẹ̀lé Wa",
    allRights: "Gbogbo ẹtọ wa.", searchPlaceholder: "Wà nípa orúkọ, irú...",
    filters: "Àlẹmọ", clearFilters: "Pa Àlẹmọ", piecesFound: "àwọn ege ri",
    category: "Ẹka", color: "Àwọ", priceRange: "Iye Owó", purchase: "Ra",
    aboutPageHeroSub: "Ti a bí ní Lagos. Ti a wọ ní gbogbo aye.", aboutPageEst: "Ti dásílẹ̀ 2012",
    theVision: "Ìrísí", craftingElegance: "Ṣíṣe Ẹwà Láti Ìbẹ̀rẹ̀",
    visionP1: "O.V Styles ni a dá sí látọwọ́ ifẹ́ fún ìdúróṣinṣin àti ọ̀wọ̀ tó jinlẹ̀ fún ìdámọ̀ Áfríkà.",
    visionP2: "Àwa kò lepa àṣà. Àwa ń ṣe ẹwu tí yóò pẹ́ jù ìgbà tí a bí wọn.",
    philosophyLabel: "Ìmọ̀-ọgbọ́n", philosophyHeading: "Aṣọ pẹ̀lú Ìtumọ̀",
    philosophyP1: "Àwa gbàgbọ́ nínú ìtàjẹsílẹ̀ tí ó ṣe pàtàkì, tí ó ń ṣe àwọn ẹwu tí ó ń bọ̀wọ̀ fún àwọn ọgbọ́n-iṣẹ́.",
    philosophyP2: "Láti ìpamọ́ àwọn asọ tí ó dára jùlọ títí di àwọn alaye ikẹyìn, ilana wa ń bọ̀wọ̀ fún haute couture.",
    founderQuote: "Ẹwu kọọkan tí a ṣe jẹ́ lẹ́tà ifẹ́ sí àṣà Áfríkà, tí a kọ nínú okùn àti asọ.",
    founderQuoteAttr: "Òṣìṣẹ́ Ìgbékalẹ̀, O.V Styles",
    journeyLabel: "Ìrìn-Àjò", ourMilestones: "Àwọn Àṣeyọrí Wa",
    m1: "O.V Styles ti dásílẹ̀ ní Lagos, Nigeria", m2: "Ìfihàn àkọ́kọ́ ní Lagos Fashion Week",
    m3: "Ti ṣe aṣọ fún olókìkí àkọ́kọ́ fún àyẹyẹ ńlá", m4: "Ti gba àwọn àṣẹ ìjọba àgbáyé",
    m5: "Ti ṣe àgbéjáde akojopo online", m6: "500+ ẹwu bespoke, 50+ àwọn onibàárà pàtàkì",
    directorLabel: "Òṣìṣẹ́ Ìgbékalẹ̀", directorHeading: "Ayáwòrán O.V Styles",
    directorFullBio1: "Ọkàn tí ó wà lẹ́yìn O.V Styles gbé àwọn ẹka méjì papọ̀: àṣọ àti ẹ̀rọ kọmputa.",
    directorFullBio2: "Ó ṣe àpẹrẹ O.V Styles gẹ́gẹ́ bí iṣẹ́ ìgbékalẹ̀ tí a kọ́ pẹ̀lú ìmọ̀-ẹ̀rọ.",
    directorFullBio3: "Ìrísí rẹ̀ jẹ́ ìrọrùn àti àìní àfikún: ìtàjẹsílẹ̀ Áfríkà kò yẹ kí ó jẹ́ àfẹ́. Ó yẹ kí ó jẹ́ ìdiwọ̀n.",
    aboutVal1Title: "Ọgbọ́n-Iṣẹ́", aboutVal1Desc: "Aṣọ kọọkan ti pari pẹlu ìdúróṣinṣin.",
    aboutVal2Title: "Ẹwà", aboutVal2Desc: "Àwọn àpẹrẹ wa ṣàfihàn ẹwà aláìgbédègbéyọ̀.",
    aboutVal3Title: "Ohun-Ìní", aboutVal3Desc: "A ṣe ayẹyẹ ohun-ìní Áfríkà nípasẹ̀ àpẹrẹ ìgbàlódé.",
    workWithUs: "Ṣiṣẹ́ Pẹ̀lú Wa", createSomething: "Jẹ́ Kí A Ṣe Nǹkan Ìyanu",
    createDesc: "Bí o bá ń wá aṣọ tàbí ń ṣàwárí akojopo wa, a gbàwọlé gbogbo ìjíròrò.",
    shopCollection: "Ra Akojopo", getInTouch: "Kan Sí Wa",
    contactPageHeroSub: "Àwa fẹ́ gbọ́ lọ́wọ́ rẹ.", contactPageEst: "Lagos, Nigeria",
    getInTouchHeading: "Kan Sí Wa", getInTouchDesc: "Bí o bá ń wá aṣọ bespoke, ìpinnu, tàbí ó fẹ́ mọ̀ nípa iṣẹ́ wa, kan sí wa a yóò dáhùn ní 24 wákàtí.",
    sendMessage: "Firanṣẹ Ìjọ̀sí", messageSent: "Ìjọ̀sí Gba",
    messageSentDesc: "A dúpẹ́ fún ìkánlọwọ́ rẹ. Àwa yóò kan sí ọ ní 24 wákàtí.",
    formName: "Orúkọ Kíkún", formEmail: "Adírẹ́sì Ìmẹ́èlì", formPhone: "Nọ́mbà Fóònù",
    formSubject: "Ìjẹnùmọ̀", formMessage: "Ìjọ̀sí Rẹ",
    formNamePlaceholder: "Orúkọ kíkún rẹ", formEmailPlaceholder: "imeeli@rẹ.com",
    formPhonePlaceholder: "+234 800 000 0000", formSubjectPlaceholder: "Báwo ni a ṣe lè ràn ọ́ lọ́wọ́?",
    formMessagePlaceholder: "Sọ fún wa nípa àyẹyẹ rẹ tàbí aṣọ tí o fẹ́...",
    formSending: "Fíránṣẹ...", formSend: "Firanṣẹ Ìjọ̀sí",
    formSubjectOpt1: "Aṣọ Bespoke", formSubjectOpt2: "Ṣe Ipinnu Fitting",
    formSubjectOpt3: "Ìbéèrè Gbogbogbò", formSubjectOpt4: "Àjọṣepọ̀ / Atẹ̀jáde",
    visitUs: "Ṣàbẹwò Atelier", callUs: "Pe Wa", emailUs: "Ìmẹ́èlì Wa",
    hoursLabel: "Àkókò Atelier", hoursValue: "Ẹtì – Àbámẹ́ta, 9owúrọ̀ – 6alẹ̀ WAT",
    whatsappUs: "Ìjọ̀sí lórí WhatsApp", whatsappDesc: "Fẹ́ ìdáhùn yára? Firanṣẹ ìjọ̀sí lórí WhatsApp.",
    messageOnWhatsapp: "Ṣí WhatsApp",
    faqLabel: "FAQ", faqHeading: "Àwọn Ìbéèrè Wọ́pọ̀",
    faq1Q: "Ìgbà mélòó ni aṣọ bespoke máa ń gba?", faq1A: "Aṣọ bespoke máa ń gba ọ̀sẹ̀ 2 sí 6 da lórí ìdíyelé àpẹrẹ.",
    faq2Q: "Ṣé o ní aṣọ ready-to-wear?", faq2A: "Bẹ́ẹ̀ni. Akojopo ready-to-wear wa lórí àtẹ̀jáde ní ìwọ̀n dídínwọ́n.",
    faq3Q: "Ṣé mo lè ṣe fitting ṣáájú ìgbẹ̀kẹ̀lé?", faq3A: "Dájúdájú. A gbàiyọ ìfọ̀rọ̀wánilẹ́nuwò àkọ́kọ́ láti mọ àfẹ́ rẹ daradara.",
    faq4Q: "Ṣé ẹ ń rán aṣọ lọ sí ẹlòmíì?", faq4A: "Bẹ́ẹ̀ni, a ń jiṣẹ́ sí Nigeria àti àgbáyé. Àkókò jiṣẹ́ yóò jẹ́ ìmúdájú ní àkókò àṣẹ.",
    addToCart: "Fi sí Àgbon", addedToCart: "Ti Fi", removeFromCart: "Yọ Kuro",
    cart: "Àgbon", cartEmpty: "Àgbon rẹ ò ní nǹkan", cartEmptyDesc: "Ṣàwárí akojopo kí o sì fi àwọn aṣọ tí o fẹ́ síi.",
    cartTotal: "Àpapọ̀", checkoutWhatsapp: "Sanwó lórí WhatsApp", continueShopping: "Tẹsiwaju Rírà",
    qty: "Iye", itemsInCart: "àwọn ege ní àgbon", clearCart: "Pa Àgbon",
    loved: "Fẹ́rẹ̀", loves: "fẹ́rẹ̀", itemLoved: "O fẹ́ aṣọ yìí",
    filterAll: "Gbogbo", sortBy: "Ṣe Títọsọ", sortNewest: "Tuntun Jùlọ", sortPriceLow: "Iye: Kékeré sí Àgbà", sortPriceHigh: "Iye: Àgbà sí Kékeré", sortMostLoved: "Tí A Fẹ́ Jùlọ",
    noItemsFound: "Kò sí aṣọ tí a rí", searchItems: "Wà àwọn aṣọ...",
  },
     ig: {home: "Ulo", about: "Maka Anyị", marketplace: "Ahịa", contact: "Kpọtụrụ Anyị",
    exploreCollection: "Chọpụta Nchịkọta", bookFitting: "Dee Nkwado",
    tagline: "Ebe Ọdịnala Zute Uwe Dị Ọnụ Ala", tagline2: "Akwara maka Oge Niile",
    tagline3: "Emere ya nke ọma, Yi ya na Otù", tagline4: "Ụdị Afrika Oge Ugbu a", tagline5: "Ụkwụ Ọ bụla Na-akọ Akụkọ",
    newCollection: "Nchịkọta Ọhụrụ", collection: "Nchịkọta", newSeason: "Oge Ọhụrụ",
    featuredPieces: "Uwe Pụtara Ìhè",
    featuredDesc: "Ahọpụtara n'aka n'aka site na atelier anyị ugbu a — ihe ọ bụla bụ njikọ nke omenala, couture, na ihe ọhụrụ.",
    shopByCategory: "Zụta Site na Udi", viewCollection: "Hụ Nchịkọta Niile",
    ourStory: "Akụkọ Anyị", readMore: "Gụọ Ọzọ",
    aboutHeading: "Maka O.V Styles",
    aboutP1: "O.V Styles bụ ụlọ ọrụ uwe dị na Lagos na-adabere n'imepụta uwe nke mma na-adịgide — iberibe na-asọpụrụ ihe ọmụma Afrika na-achị uche n'ụwa.",
    aboutP2: "Site na ọrụ bespoke ruo nchịkọta ready-to-wear, atelier anyị aghọwola aha a tụkwasịrị obi n'etiti ndị ahịa na-amata ihe dị oke mkpa n'Nigeria na diaspora.",
    yearsLabel: "Afọ", designsLabel: "Nhazi", clientsLabel: "Ndị Ahịa",
    theVisionary: "Onye Ọlụlụ Anya", meetDirector: "Zuo Onye Nduzi Ihe Okike",
    ceoTitle: "Onye Nduzi Ihe Okike", ceoSubtitle: "O.V Styles · Lagos, Nigeria",
    mindBehind: "Uche Dị n'Azụ Akara", codeAndCouture: "Ebe Koodu Zutere Uwe",
    ceoBio1: "Ike ihe okike dị n'azụ O.V Styles bụ ụdị pụrụ iche — onye ọlụlụ anya uwe nke dị mma n'ide koodu backend dị ka ọ dị n'ise atụmatụ uwe silk.",
    ceoBio2: "Ọmụmụihe ya abụọ na-enye O.V Styles ohere ịrụ ọrụ n'ebe ọdịnala na teknụzụ zutere — ebe ntụpọ aka zutere ọgụgụ isi nhazi.",
    tagHauteCouture: "Haute Couture", tagTechDesign: "Nhazi Teknụzụ", tagAfricanLuxury: "Ọchịchọ Afrika",
    fullStory: "Akụkọ Nke Ọzọ",
    whatWeStandFor: "Ihe Anyị Na-eguzosi Ike N'elu", ourValues: "Ụkpụrụ Anyị",
    val1Title: "Nka", val1Desc: "Uwe ọ bụla na-agwụcha aka aka — ebe mkpebi ọ bụla adịghị pere mpe.",
    val2Title: "Ọmụmụihe", val2Desc: "Dabere n'ọchịchọ omenala akwa Afrika, nhazi ọ bụla na-ejikọ ihe mbụ na nke oge a.",
    val3Title: "Pụrụ iche", val3Desc: "Mwepụta dị oke oke na-eme ka onye ahịa ọ bụla nweta ihe nke ya n'ezie.",
    howItWorks: "Otú Ọ Si Arụ Ọrụ", bespokeProcess: "Usoro Bespoke",
    step1Title: "Mkparịta Ụka", step1Desc: "Anyị na-amalite n'okwu omimi — ịchọpụta ọhụụ gị, ememe, na nkwupụta i chọrọ ime.",
    step2Title: "Nhazi", step2Desc: "Ndị otu ihe okike anyị na-atụgharị echiche gị ka ọ bụrụ atụmatụ nke ọma.",
    step3Title: "Ọrụ", step3Desc: "Ndị nkụ aka ọkachamara na-eme nhazi ọ bụla ka ọ dị ndụ site na ihe ndị dị elu.",
    step4Title: "Nnyefe", step4Desc: "Ihe emechara a na-enye ya ya na oge nyocha ikpeazụ — iji hụ na ọ dị mma ọ bụla.",
    clientLove: "Ifunanya Ndị Ahịa", whatTheySay: "Ihe Ha Na-ekwu",
    t1Quote: "O.V Styles were m uwe maka alụmdi na nwunye m, a nọọ m mma dị ka eze. Nka dị ike n'Lagos niile.",
    t1Name: "Amara O.", t1Title: "Nwunye Ọhụrụ · Lagos",
    t2Quote: "Eviela m akara ụwa, ma ọ dịghị ihe sọ asọ na ọ dị mma nke O.V Styles na-enye.",
    t2Name: "Chidinma E.", t2Title: "Ọkọwa TV · Abuja",
    t3Quote: "Ihe ọ bụla na-ebu akụkọ. A na-atọ m mma n'oge ọ bụla m si na uwe ha pụta.",
    t3Name: "Fatima B.", t3Title: "Onye Ọchụnta Ego · Kano",
    discoverLatest: "Chọpụta Nchịkọta Ọhụrụ",
    discoverText: "Chọpụta uwe dị mma emere ya n'ịhụnanya na nlezianya maka onye ọrụ uwe oge a.",
    shopNow: "Zụta Ugbu a",
    newsletterTitle: "Sonye O.V Styles", newsletterDesc: "Bụrụ nke mbụ ịmara maka nchịkọta ọhụrụ.",
    emailPlaceholder: "Adreesị email gị", subscribe: "Debanye Aha",
    quickLinks: "Njikọ Ngwa Ngwa", contactUs: "Kpọtụrụ Anyị", followUs: "Soro Anyị",
    allRights: "Ikike niile echekwara.", searchPlaceholder: "Chọọ site na aha, udi...",
    filters: "Nzacha", clearFilters: "Hichapụ Nzacha", piecesFound: "ihe achọtara",
    category: "Udi", color: "Agba", priceRange: "Oke Ọnụ Ahịa", purchase: "Zụta",
    aboutPageHeroSub: "Amụrụ na Lagos. Yi n'ụwa niile.", aboutPageEst: "Guzobere 2012",
    theVision: "Ọhụụ", craftingElegance: "Na-emepụta Mma Kemgbe Mmalite",
    visionP1: "O.V Styles amụrụ site na ifunanya maka nlezianya na nkwanye ùgwù maka ihe ọmụma Afrika.",
    visionP2: "Anyị anaghị achụso ụdị. Anyị na-eme uwe ga-adịgide karịa oge amụrụ ha.",
    philosophyLabel: "Echiche", philosophyHeading: "Uwe nwere Ihe Ọ Pụtara",
    philosophyP1: "Anyị kwenyere na ọchịchọ na-adịgide, na-emepụta uwe dị mma na-asọpụrụ ndị ọrụ aka.",
    philosophyP2: "Site na nchekwa akwa ndị kacha mma ruo ọkwa ikpeazụ, usoro anyị na-asọpụrụ haute couture.",
    founderQuote: "Uwe ọ bụla anyị na-emepụta bụ akwụkwọ ifunanya nye omenala Afrika, deere na eriri na akwa.",
    founderQuoteAttr: "Onye Nduzi Ihe Okike, O.V Styles",
    journeyLabel: "Njem", ourMilestones: "Ihe Anyị Nwetara",
    m1: "O.V Styles guzobere na Lagos, Nigeria", m2: "Nchọpụta nke mbụ na Lagos Fashion Week",
    m3: "Bịara na onye ama ama maka ememe ukwu", m4: "Gbasaa ọrụ wee malite ọrụ mba ụwa",
    m5: "Webata nchịkọta ready-to-wear online", m6: "500+ uwe bespoke, ndị ahịa 50+ a kọwara",
    directorLabel: "Onye Nduzi Ihe Okike", directorHeading: "Onye Nnọchite Anya O.V Styles",
    directorFullBio1: "Uche dị n'azụ O.V Styles jikọtara ngalaba abụọ: uwe na injinia kọmputa.",
    directorFullBio2: "O zapụtara O.V Styles dị ka ọrụ ihe okike ewuputara n'ụzọ ọhụrụ.",
    directorFullBio3: "Ọhụụ ya dị mfe ma ọ nweghị mgbagha: ọchịchọ Afrika ekwesịghị ịbụ ihe atọ ụtọ. Ọ kwesịrị ịbụ ọkọlọtọ.",
    aboutVal1Title: "Nka", aboutVal1Desc: "Uwe ọ bụla na-agwụcha aka aka.",
    aboutVal2Title: "Mma", aboutVal2Desc: "Nhazi anyị gosipụtara mma na-adịgide.",
    aboutVal3Title: "Ọmụmụihe", aboutVal3Desc: "Anyị na-emejuputa omenala Afrika site na nhazi oge a.",
    workWithUs: "Rụọ Ọrụ na Anyị", createSomething: "Ka Anyị Mepụta Ihe Dị Egwu",
    createDesc: "Ma ọ bụ na ị na-achọ uwe pụrụ iche ma ọ bụ na ị na-achọpụta nchịkọta, anyị na-anabata ajụjụ ọ bụla.",
    shopCollection: "Zụta Nchịkọta", getInTouch: "Kpọtụrụ Anyị",
    contactPageHeroSub: "Anyị nọ ebe a imere gị.", contactPageEst: "Lagos, Nigeria",
    getInTouchHeading: "Kpọtụrụ Anyị", getInTouchDesc: "Ma ọ bụ na ị na-achọ uwe bespoke, oge nyocha, ma ọ bụ ị ciekwu maka ọrụ anyị, kpọtụrụ anyị, anyị ga-azaghachi na 24 awa.",
    sendMessage: "Zipu Ozi", messageSent: "Ozi Natara",
    messageSentDesc: "Daalụ maka ikwutere anyị. Anyị ga-akpọtụrụ gị n'ime 24 awa.",
    formName: "Aha Zuru Oke", formEmail: "Adreesị Email", formPhone: "Nọmba Ekwe",
    formSubject: "Isiokwu", formMessage: "Ozi Gị",
    formNamePlaceholder: "Aha zuru oke gị", formEmailPlaceholder: "email@gị.com",
    formPhonePlaceholder: "+234 800 000 0000", formSubjectPlaceholder: "Kedu ka anyị ga-enyere gị aka?",
    formMessagePlaceholder: "Gwa anyị maka ememe gị ma ọ bụ uwe i chọrọ n'uche...",
    formSending: "Na-eziga...", formSend: "Zipu Ozi",
    formSubjectOpt1: "Ọrụ Bespoke", formSubjectOpt2: "Dee Oge Nyocha",
    formSubjectOpt3: "Ajụjụ Ọzọ", formSubjectOpt4: "Mmekọ / Nta",
    visitUs: "Bịa Atelier", callUs: "Kpọọ Anyị", emailUs: "Zipu Anyị Email",
    hoursLabel: "Oge Atelier", hoursValue: "Mọn – Sat, 9 ụtụtụ – 6 abali WAT",
    whatsappUs: "Zipu Anyị Ozi na WhatsApp", whatsappDesc: "Chọrọ nzaghachi ngwa ngwa? Zipu anyị ozi na WhatsApp.",
    messageOnWhatsapp: "Mepee WhatsApp",
    faqLabel: "FAQ", faqHeading: "Ajụjụ A Na-ajụkarị",
    faq1Q: "Ọ na-ewe oge ole imepụta uwe bespoke?", faq1A: "Ọrụ bespoke na-ewe izu 2 ruo 6 dabere na ọnụ nhazi.",
    faq2Q: "Ị nwere uwe ready-to-wear?", faq2A: "Ee. Nchịkọta ready-to-wear anyị dị na ụlọ ahịa na ọnụ ọgụgụ dị oke.",
    faq3Q: "Enwere m ike ịdee oge nyocha tupu ịkwado?", faq3A: "Dị mma. Anyị na-akwado mkparịta ụka mbụ iji ghọta ọhụụ gị nke ọma.",
    faq4Q: "Ị na-ebuga ihe ịzụ ahịa mba ụwa?", faq4A: "Ee, anyị na-eziga na Nigeria na mba ụwa. A ga-akwado oge na ọnụ ahịa na oge ịzụ.",
    addToCart: "Tinye na Igwe", addedToCart: "Atinyere", removeFromCart: "Wepu",
    cart: "Igwe", cartEmpty: "Igwe gị dị efu", cartEmptyDesc: "Chọpụta nchịkọta wee tinye ihe ị hụrụ n'anya.",
    cartTotal: "Ngụkọta", checkoutWhatsapp: "Kwuo Ụgwọ na WhatsApp", continueShopping: "Gaa n'ihu Ịzụ",
    qty: "Ọnụ", itemsInCart: "ihe na igwe", clearCart: "Hichapụ Igwe",
    loved: "Hụrụ n'Anya", loves: "hụrụ n'anya", itemLoved: "Ị hụrụ uwe a n'anya",
    filterAll: "Niile", sortBy: "Hazie site", sortNewest: "Ọhụrụ Kacha", sortPriceLow: "Ọnụ: Ala ruo Elu", sortPriceHigh: "Ọnụ: Elu ruo Ala", sortMostLoved: "Kacha Hụrụ n'Anya",
    noItemsFound: "Achọtaghị uwe", searchItems: "Chọọ uwe...",
  },
  ha: {
    home: "Gida", about: "Game Da Mu", marketplace: "Kasuwa", contact: "Tuntuɓe Mu",
    exploreCollection: "Bincika Tarin", bookFitting: "Yi Alƙawari",
    tagline: "Inda Al'ada Take Haɗuwa da Zamani", tagline2: "An Yi ta don Kowane Lokaci",
    tagline3: "An Kira ta da Kyau, Ana Sa ta da Alfahari", tagline4: "Salon Afirka na Zamani", tagline5: "Kowane Ɗinki Yana Labari",
    newCollection: "Sabon Tarin", collection: "Tarin", newSeason: "Sabon Lokaci",
    featuredPieces: "Tufafi Masu Daraja",
    featuredDesc: "An zaɓi su daga ɗakin ƙirƙira mu na yanzu — kowane yanki haɗin al'ada, couture, da fasaha ta zamani.",
    shopByCategory: "Siya ta Nau'i", viewCollection: "Dubi Dukkan Tarin",
    ourStory: "Labarin Mu", readMore: "Karanta Ƙari",
    aboutHeading: "Game da O.V Styles",
    aboutP1: "O.V Styles ɗakin tufafi ne da ke Lagos wanda ke sadaukar da kansa wajen ƙirƙirar tufafi na dindindin — guntuna da ke girmama al'adar Afirka tare da jan hankalin duniya.",
    aboutP2: "Daga ayyukan bespoke zuwa tattarawa ready-to-wear, ɗakin ƙirƙira mu ya zama suna mai dogaro a tsakanin abokan ciniki a Najeriya da diaspora.",
    yearsLabel: "Shekaru", designsLabel: "Zane-zane", clientsLabel: "Abokan Ciniki",
    theVisionary: "Mai Hangen Nesa", meetDirector: "Haɗu da Daraktan Kirkire-kirkire",
    ceoTitle: "Daraktan Kirkire-kirkire", ceoSubtitle: "O.V Styles · Lagos, Nigeria",
    mindBehind: "Tunanin Da ke Bayan Alamar", codeAndCouture: "Inda Kodin Ya Haɗu da Tufafi",
    ceoBio1: "Ƙarfin kirkire-kirkire da ke bayan O.V Styles mutum ne na musamman — mai hangen nesa na tufafi wanda ya fi ƙwarewa a rubutun backend kamar yadda yake zana siliki.",
    ceoBio2: "Ƙwarewarsa biyu ta ba O.V Styles damar yin aiki a mahaɗar al'ada da fasaha — inda aikin hannu ya haɗu da hankali na zane.",
    tagHauteCouture: "Haute Couture", tagTechDesign: "Zane da Fasaha", tagAfricanLuxury: "Ɗaukaka ta Afirka",
    fullStory: "Cikakken Labari",
    whatWeStandFor: "Abin Da Muke Tsayawa Dominsa", ourValues: "Ƙimominmu",
    val1Title: "Gwaninta", val1Desc: "Kowane tufafi ana ƙarawa da hannu da daidaito — inda babu ƙaramin abu da ake wuce da shi.",
    val2Title: "Gado", val2Desc: "Da tushe a cikin arziki na al'adar masaka ta Afirka, kowane zane yana haɗa tsohon fasaha da zamani.",
    val3Title: "Musammantar", val3Desc: "Iyakataccen samarwa yana tabbatar da cewa kowane abokin ciniki ya sami wani abu na musamman.",
    howItWorks: "Yadda Yake Aiki", bespokeProcess: "Tsarin Bespoke",
    step1Title: "Shawarwari", step1Desc: "Muna fara da zuzzurfan tattaunawa — bincika ra'ayinka, bikin, da saƙon da kake son isar da shi.",
    step2Title: "Zane", step2Desc: "Ƙungiyar kirkire-kirkire mu tana fassara niyarku zuwa zane-zane masu cikakken bayani.",
    step3Title: "Ƙirƙira", step3Desc: "Ƙwararrun maɗinkai suna kawo kowane zane zuwa rayuwa ta amfani da kayan aiki na farko.",
    step4Title: "Isar", step4Desc: "Ana isar da ɗinkin da aka kammala tare da zaman ƙarshe — don tabbatar da sakamakon da ba a tantama ba.",
    clientLove: "Ƙaunar Abokan Ciniki", whatTheySay: "Abin da Suka Ce",
    t1Quote: "O.V Styles sun yi mini tufafi don aurenmu kuma na ji kamar sarauniya. Gwaninta ba ta da misali a kowane wuri a Lagos.",
    t1Name: "Amara O.", t1Title: "Amarya · Lagos",
    t2Quote: "Na sanya manyan alamomin duniya, amma babu abin da ya yi kama da taɓawar mutum da ingancin O.V Styles.",
    t2Name: "Chidinma E.", t2Title: "Sanannen TV · Abuja",
    t3Quote: "Kowane yanki yana ɗauke da labari. Ina samun yabon da babu ƙetarewa kowane lokaci da na fito suna sanya zane-zanensu.",
    t3Name: "Fatima B.", t3Title: "Mai Kasuwanci · Kano",
    discoverLatest: "Gano Sabon Tarin",
    discoverText: "Gano kyawawan tufafi da aka yi da sha'awa da daidaito don ƙwararren mai son kayan kwalliya na zamani.",
    shopNow: "Siya Yanzu",
    newsletterTitle: "Shiga Rukunin O.V Styles", newsletterDesc: "Kasance na farko don sanin sabbin tarurruka.",
    emailPlaceholder: "Adireshin imel ɗinka", subscribe: "Yi Rajista",
    quickLinks: "Hanyoyin Gajerun", contactUs: "Tuntuɓe Mu", followUs: "Bimu",
    allRights: "Dukkan haƙƙoƙi an kiyaye su.", searchPlaceholder: "Nema ta suna, nau'i...",
    filters: "Tace", clearFilters: "Share Tacewa", piecesFound: "an samu",
    category: "Nau'i", color: "Launi", priceRange: "Kewayon Farashi", purchase: "Siya",
    aboutPageHeroSub: "An haife ta a Lagos. Ana sa ta a duk duniya.", aboutPageEst: "An kafa 2012",
    theVision: "Hangen Nesa", craftingElegance: "Ƙirƙirar Kyau Tun Farko",
    visionP1: "An haifi O.V Styles daga sha'awar daidaito da zurfin girmama asalin Afirka.",
    visionP2: "Ba mu bin salon ba. Muna yin tufafi da za su wuce lokacin da aka haife su.",
    philosophyLabel: "Falsafa", philosophyHeading: "Salon tare da Manufa",
    philosophyP1: "Muna imani da ɗaukaka mai ɗorewa, ƙirƙirar kyawawan tufafi da ke girmama masu sana'a.",
    philosophyP2: "Daga samun kyawawan yardir zuwa ƙarshen alamu da aka yi da hannu, tsarinmu yana girmama haute couture.",
    founderQuote: "Kowane tufafi da muke ƙirƙira wasiƙa ce ta ƙauna ga al'adar Afirka, written in thread and fabric.",
    founderQuoteAttr: "Daraktan Kirkire-kirkire, O.V Styles",
    journeyLabel: "Tafiya", ourMilestones: "Abubuwan Da Muka Cimma",
    m1: "An kafa O.V Styles a Lagos, Nigeria", m2: "Nuna farko a Lagos Fashion Week",
    m3: "Sun sa tufafi wa sanannen mutum a wani babban bikin", m4: "Sun faɗaɗa da fara alƙawurai na ƙasa da ƙasa",
    m5: "Sun ƙaddamar da tarin ready-to-wear a layi", m6: "500+ bespoke, abokan ciniki 50+ na musamman",
    directorLabel: "Daraktan Kirkire-kirkire", directorHeading: "Masanin O.V Styles",
    directorFullBio1: "Tunanin da ke bayan O.V Styles ya haɗu da fannonin biyu: tufafi da injiniyan kwamfuta.",
    directorFullBio2: "Ya tsara O.V Styles a matsayin aikin kirkire-kirkire wanda aka gina da hankali.",
    directorFullBio3: "Hangen nesansa yana da sauƙi kuma ba ya rangwamen: ɗaukakan Afirka bai kamata ya zama burin ba. Ya kamata ya zama ma'auni.",
    aboutVal1Title: "Gwaninta", aboutVal1Desc: "Kowane tufafi ana ƙarawa da hannu da daidaito.",
    aboutVal2Title: "Kyau", aboutVal2Desc: "Zane-zanenmu sun nuna kyaun da ba ya tsufa.",
    aboutVal3Title: "Gado", aboutVal3Desc: "Muna murnar gadon Afirka ta hanyar zane na zamani.",
    workWithUs: "Yi Aiki Tare da Mu", createSomething: "Bari Mu Ƙirƙiri Wani Abu Mai Ban Mamaki",
    createDesc: "Ko kuna neman tufafi na musamman ko kuna bincika tarin, muna maraba da kowane tattaunawa.",
    shopCollection: "Siya Tarin", getInTouch: "Tuntuɓe Mu",
    contactPageHeroSub: "Muna son jin daga gare ku.", contactPageEst: "Lagos, Nigeria",
    getInTouchHeading: "Tuntuɓe Mu", getInTouchDesc: "Ko kuna yin bespoke, alƙawarin fitting, ko kuna son sanin aikinmu, tuntuɓe mu za mu amsa cikin 24 sa'o'i.",
    sendMessage: "Aika Saƙo", messageSent: "An Karɓi Saƙo",
    messageSentDesc: "Muna godiya da tuntuɓar ku. Za mu tuntube ku cikin 24 sa'o'i.",
    formName: "Cikakken Suna", formEmail: "Adireshin Imel", formPhone: "Lambar Waya",
    formSubject: "Batun", formMessage: "Saƙonku",
    formNamePlaceholder: "Cikakken sunan ku", formEmailPlaceholder: "imel@ku.com",
    formPhonePlaceholder: "+234 800 000 0000", formSubjectPlaceholder: "Yaya za mu taimake ku?",
    formMessagePlaceholder: "Faɗa mana game da bikin ku ko tufafin da kuke tunanin...",
    formSending: "Ana aikawa...", formSend: "Aika Saƙo",
    formSubjectOpt1: "Bespoke Commission", formSubjectOpt2: "Ƙaddamar da Fitting",
    formSubjectOpt3: "Tambaya Gabaɗaya", formSubjectOpt4: "Haɗin gwiwa / Manema labarai",
    visitUs: "Ziyarci Atelier", callUs: "Kira Mu", emailUs: "Imel Mu",
    hoursLabel: "Lokacinmu", hoursValue: "Lit – Asabar, 9 safe – 6 yamma WAT",
    whatsappUs: "Aika Saƙo a WhatsApp", whatsappDesc: "Kuna son amsa da sauri? Aika mana saƙo kai tsaye a WhatsApp.",
    messageOnWhatsapp: "Buɗe WhatsApp",
    faqLabel: "FAQ", faqHeading: "Tambayoyi Gama Gari",
    faq1Q: "Tsawon lokaci nawa ne ake yin bespoke?", faq1A: "Commissions na bespoke yawanci suna ɗaukar makonni 2 zuwa 6 dangane da rikitarwa.",
    faq2Q: "Kuna da tufafi ready-to-wear?", faq2A: "Ee. Tarin ready-to-wear ɗinmu yana samuwa a cikin ƙayyadaddun yawan.",
    faq3Q: "Zan iya yin fitting kafin alƙawari?", faq3A: "Tabbas. Muna ƙarfafawa farkon shawarwari kafin kowace alƙawari.",
    faq4Q: "Kuna jigilar kaya zuwa ƙasashen waje?", faq4A: "Ee, muna aika kaya zuwa Nigeria da ƙasashen waje. Za a tabbatar da lokacin jigilar kaya da farashi.",
    addToCart: "Ƙara zuwa Kwandon", addedToCart: "An Ƙara", removeFromCart: "Cire",
    cart: "Kwando", cartEmpty: "Kwandon ku bai cika ba", cartEmptyDesc: "Bincika tarin ka ƙara abubuwan da kuke son.",
    cartTotal: "Jimla", checkoutWhatsapp: "Biya ta WhatsApp", continueShopping: "Ci gaba da Siya",
    qty: "Yawa", itemsInCart: "kayan da ke kwando", clearCart: "Share Kwando",
    loved: "An So", loves: "suna so", itemLoved: "Kun so wannan tufafin",
    filterAll: "Duka", sortBy: "Tsarawa ta", sortNewest: "Sabon", sortPriceLow: "Farashi: Ƙasa zuwa Sama", sortPriceHigh: "Farashi: Sama zuwa Ƙasa", sortMostLoved: "Mafi So",
    noItemsFound: "Ba a sami tufafi ba", searchItems: "Nema tufafi...",
  },
  urh: {
    home: "Oke", about: "Rerin Ai", marketplace: "Ọtọ", contact: "Ro Ai",
    exploreCollection: "Rọ Ọwọ", bookFitting: "Kọ Ẹdẹ",
    tagline: "Ibi Ti Ọdọ Pade Igbalode", tagline2: "Rẹrin fun Gbogbo Akoko",
    tagline3: "Ẹwu Ti A Ṣe Daradara", tagline4: "Ara Afrika Ode Oni", tagline5: "Gbogbo Iṣẹ Sọ Itan",
    newCollection: "Ọwọ Tuntun", collection: "Ọwọ", newSeason: "Akoko Tuntun",
    featuredPieces: "Ẹwu Pataki",
    featuredDesc: "Ti a yan lati inu atelier wa — ẹwu kọọkan jẹ apapọ aṣa ati iṣẹ-ọnà ode oni.",
    shopByCategory: "Rẹ nọ Udi", viewCollection: "Wo Ọwọ Pataki",
    ourStory: "Itan Ai", readMore: "Gbe Siwaju",
    aboutHeading: "Nipa O.V Styles",
    aboutP1: "O.V Styles jẹ ile-aṣọ ni Lagos ti o ṣe igbẹhin si ṣiṣe awọn ẹwu ti o ni ẹwà — awọn ẹwu ti o ṣe ola fun aṣa Afrika.",
    aboutP2: "Lati awọn aṣọ bespoke titi di awọn akojọpo ready-to-wear, atelier wa ti di orukọ igbẹkẹle laarin awọn alabara kọja Nigeria.",
    yearsLabel: "Ọdún", designsLabel: "Àpẹrẹ", clientsLabel: "Àwọn Onibàárà",
    theVisionary: "Olóye", meetDirector: "Pàdé Òṣìṣẹ́ Ìgbékalẹ̀",
    ceoTitle: "Òṣìṣẹ́ Ìgbékalẹ̀", ceoSubtitle: "O.V Styles · Lagos, Nigeria",
    mindBehind: "Ọkàn Lẹ́yìn Àmì", codeAndCouture: "Ibi Ti Kóòdù Pàdé Ẹwu",
    ceoBio1: "Agbára ìgbékalẹ̀ tí ó wà lẹ́yìn O.V Styles jẹ́ ẹni àkànṣe — alájọsọ́ tí ó mọ iṣẹ́-ẹ̀rọ kọmputa àti ṣíṣe ẹwu dọ́gba.",
    ceoBio2: "Ìmọ̀ rẹ̀ méjì gba O.V Styles láàyè láti ṣiṣẹ́ ni ibi tí àṣà ìbílẹ̀ pàdé ìmọ̀-ẹ̀rọ.",
    tagHauteCouture: "Haute Couture", tagTechDesign: "Àpẹrẹ Ìmọ̀-ẹ̀rọ", tagAfricanLuxury: "Ìtàjẹsílẹ̀ Áfríkà",
    fullStory: "Ìtàn Kíkún",
    whatWeStandFor: "Ohun Tí A Dúró Fún", ourValues: "Àwọn Ìdásílẹ̀ Wa",
    val1Title: "Ọgbọ́n-Iṣẹ́", val1Desc: "Ẹwu kọọkan ti pari pẹlu ìdúróṣinṣin.",
    val2Title: "Ohun-Ìní", val2Desc: "Ti gbé ìsìn sí ọrọ̀ àṣà aṣọ Áfríkà.",
    val3Title: "Ìyàtọ̀", val3Desc: "Àwọn ṣíṣe tí o ní àgbékalẹ̀ ní dídíwọ́n dájú pé onibàárà kọọkan gba nǹkan àkànṣe.",
    howItWorks: "Bí Ó Ṣe Ń Ṣiṣẹ́", bespokeProcess: "Ìlànà Bespoke",
    step1Title: "Ìfọ̀rọ̀wánilẹ́nuwò", step1Desc: "A bẹ̀rẹ̀ pẹ̀lú ìjíròrò jíjinlẹ̀ nípa ìrísí rẹ.",
    step2Title: "Àpẹrẹ", step2Desc: "Ẹgbẹ́ ìgbékalẹ̀ wa túmọ̀ ète rẹ sí àwọn àfihàn.",
    step3Title: "Iṣẹ́", step3Desc: "Àwọn aṣọ-olóye mú ẹwu kọọkan wá sí ìmúṣẹ.",
    step4Title: "Ìfẹsẹ̀wọnsẹ̀", step4Desc: "Ẹwu tí a pari yóò wà pẹ̀lú ìdánwò ikẹyìn.",
    clientLove: "Ifẹ Onibàárà", whatTheySay: "Ohun Tí Wọn Sọ",
    t1Quote: "O.V Styles ṣe ẹwu mi fun ìgbéyàwó mi, mo sì ní ìmọ̀lára bí ọba.",
    t1Name: "Amara O.", t1Title: "Ìyàwó · Lagos",
    t2Quote: "Mo ti wọ àwọn àmì ìtàjẹsílẹ̀ àgbáyé, ṣùgbọ́n kò sí ohun tí ó bára dé ti O.V Styles.",
    t2Name: "Chidinma E.", t2Title: "Olókìkí TV · Abuja",
    t3Quote: "Ẹwu kọọkan gbe ìtàn. Mo máa ń gba ìyin nígbà gbogbo tí mo bá wọ àpẹrẹ wọn.",
    t3Name: "Fatima B.", t3Title: "Oníṣòwò · Kano",
    discoverLatest: "Ṣàwárí Ọwọ Tuntun",
    discoverText: "Ṣàwárí àwọn ẹwu ìyanu tí a ṣe pẹ̀lú ìfẹ́ àti ìdúróṣinṣin.",
    shopNow: "Rẹ Sọ",
    newsletterTitle: "Darapọ̀ Mọ̀ O.V Styles", newsletterDesc: "Jẹ́ àkọ́kọ́ láti mọ̀ nípa àwọn ọwọ tuntun.",
    emailPlaceholder: "Adírẹ́sì ìmẹ́èlì rẹ", subscribe: "Forúkọsílẹ̀",
    quickLinks: "Àwọn Ọ̀nà", contactUs: "Ro Ai", followUs: "Tẹ̀lé Ai",
    allRights: "Gbogbo ẹtọ wa.", searchPlaceholder: "Wà nípa orúkọ...",
    filters: "Àlẹmọ", clearFilters: "Pa Àlẹmọ", piecesFound: "àwọn ege ri",
    category: "Udi", color: "Àwọ", priceRange: "Iye Owó", purchase: "Rẹ",
    aboutPageHeroSub: "Ti a bí ní Lagos. Ti a wọ ní gbogbo aye.", aboutPageEst: "Ti dásílẹ̀ 2012",
    theVision: "Ìrísí", craftingElegance: "Ṣíṣe Ẹwà Láti Ìbẹ̀rẹ̀",
    visionP1: "O.V Styles ni a dá látọwọ́ ifẹ́ fún ìdúróṣinṣin àti ọ̀wọ̀ fún ìdámọ̀ Áfríkà.",
    visionP2: "Àwa ń ṣe ẹwu tí yóò pẹ́ jù ìgbà tí a bí wọn.",
    philosophyLabel: "Ìmọ̀-ọgbọ́n", philosophyHeading: "Aṣọ pẹ̀lú Ìtumọ̀",
    philosophyP1: "Àwa gbàgbọ́ nínú ìtàjẹsílẹ̀ tí ó ṣe pàtàkì.",
    philosophyP2: "Ilana wa ń bọ̀wọ̀ fún haute couture.",
    founderQuote: "Ẹwu kọọkan tí a ṣe jẹ́ lẹ́tà ifẹ́ sí àṣà Áfríkà.",
    founderQuoteAttr: "Òṣìṣẹ́ Ìgbékalẹ̀, O.V Styles",
    journeyLabel: "Ìrìn-Àjò", ourMilestones: "Àwọn Àṣeyọrí Wa",
    m1: "O.V Styles ti dásílẹ̀ ní Lagos", m2: "Ìfihàn àkọ́kọ́ ní Lagos Fashion Week",
    m3: "Ti ṣe aṣọ fún olókìkí àkọ́kọ́", m4: "Ti gba àwọn àṣẹ àgbáyé",
    m5: "Ti ṣe àgbéjáde akojopo online", m6: "500+ ẹwu bespoke, 50+ onibàárà pàtàkì",
    directorLabel: "Òṣìṣẹ́ Ìgbékalẹ̀", directorHeading: "Ayáwòrán O.V Styles",
    directorFullBio1: "Ọkàn tí ó wà lẹ́yìn O.V Styles gbé àwọn ẹka méjì: àṣọ àti ẹ̀rọ kọmputa.",
    directorFullBio2: "Ó ṣe àpẹrẹ O.V Styles gẹ́gẹ́ bí iṣẹ́ ìgbékalẹ̀ pẹ̀lú ìmọ̀-ẹ̀rọ.",
    directorFullBio3: "Ìtàjẹsílẹ̀ Áfríkà yẹ kí ó jẹ́ ìdiwọ̀n.",
    aboutVal1Title: "Ọgbọ́n-Iṣẹ́", aboutVal1Desc: "Ẹwu kọọkan ti pari pẹlu ìdúróṣinṣin.",
    aboutVal2Title: "Ẹwà", aboutVal2Desc: "Àwọn àpẹrẹ wa ṣàfihàn ẹwà aláìgbédègbéyọ̀.",
    aboutVal3Title: "Ohun-Ìní", aboutVal3Desc: "A ṣe ayẹyẹ ohun-ìní Áfríkà nípasẹ̀ àpẹrẹ ìgbàlódé.",
    workWithUs: "Ṣiṣẹ́ Pẹ̀lú Wa", createSomething: "Jẹ́ Kí A Ṣe Nǹkan Ìyanu",
    createDesc: "A gbàwọlé gbogbo ìjíròrò.",
    shopCollection: "Ra Akojopo", getInTouch: "Kan Sí Wa",
    contactPageHeroSub: "Àwa fẹ́ gbọ́ lọ́wọ́ rẹ.", contactPageEst: "Lagos, Nigeria",
    getInTouchHeading: "Kan Sí Wa", getInTouchDesc: "Bí o bá ń wá aṣọ bespoke tàbí ó fẹ́ mọ̀ nípa iṣẹ́ wa, kan sí wa.",
    sendMessage: "Firanṣẹ Ìjọ̀sí", messageSent: "Ìjọ̀sí Gba",
    messageSentDesc: "A dúpẹ́ fún ìkánlọwọ́ rẹ. Àwa yóò kan sí ọ ní 24 wákàtí.",
    formName: "Orúkọ Kíkún", formEmail: "Adírẹ́sì Ìmẹ́èlì", formPhone: "Nọ́mbà Fóònù",
    formSubject: "Ìjẹnùmọ̀", formMessage: "Ìjọ̀sí Rẹ",
    formNamePlaceholder: "Orúkọ kíkún rẹ", formEmailPlaceholder: "imeeli@rẹ.com",
    formPhonePlaceholder: "+234 800 000 0000", formSubjectPlaceholder: "Báwo ni a ṣe lè ràn ọ́?",
    formMessagePlaceholder: "Sọ fún wa nípa àyẹyẹ rẹ tàbí aṣọ tí o fẹ́...",
    formSending: "Fíránṣẹ...", formSend: "Firanṣẹ Ìjọ̀sí",
    formSubjectOpt1: "Aṣọ Bespoke", formSubjectOpt2: "Ṣe Ipinnu Fitting",
    formSubjectOpt3: "Ìbéèrè", formSubjectOpt4: "Àjọṣepọ̀",
    visitUs: "Ṣàbẹwò Atelier", callUs: "Pe Wa", emailUs: "Ìmẹ́èlì Wa",
    hoursLabel: "Àkókò Atelier", hoursValue: "Ẹtì – Àbámẹ́ta, 9owúrọ̀ – 6alẹ̀ WAT",
    whatsappUs: "WhatsApp Wa", whatsappDesc: "Firanṣẹ ìjọ̀sí lórí WhatsApp fún ìdáhùn yára.",
    messageOnWhatsapp: "Ṣí WhatsApp",
    faqLabel: "FAQ", faqHeading: "Àwọn Ìbéèrè",
    faq1Q: "Ìgbà mélòó ni aṣọ bespoke máa ń gba?", faq1A: "Ọ̀sẹ̀ 2 sí 6 da lórí ìdíyelé àpẹrẹ.",
    faq2Q: "Ṣé o ní aṣọ ready-to-wear?", faq2A: "Bẹ́ẹ̀ni, ní ìwọ̀n dídínwọ́n.",
    faq3Q: "Ṣé mo lè ṣe fitting ṣáájú?", faq3A: "Dájúdájú. A gbàiyọ ìfọ̀rọ̀wánilẹ́nuwò àkọ́kọ́.",
    faq4Q: "Ṣé ẹ ń rán aṣọ lọ ẹlòmíì?", faq4A: "Bẹ́ẹ̀ni, Nigeria àti àgbáyé.",
    addToCart: "Fi sí Àgbon", addedToCart: "Ti Fi", removeFromCart: "Yọ Kuro",
    cart: "Àgbon", cartEmpty: "Àgbon rẹ ò ní nǹkan", cartEmptyDesc: "Ṣàwárí akojopo kí o sì fi àwọn aṣọ síi.",
    cartTotal: "Àpapọ̀", checkoutWhatsapp: "Sanwó lórí WhatsApp", continueShopping: "Tẹsiwaju Rírà",
    qty: "Iye", itemsInCart: "àwọn ege ní àgbon", clearCart: "Pa Àgbon",
    loved: "Fẹ́rẹ̀", loves: "fẹ́rẹ̀", itemLoved: "O fẹ́ aṣọ yìí",
    filterAll: "Gbogbo", sortBy: "Ṣe Títọsọ", sortNewest: "Tuntun", sortPriceLow: "Iye: Kékeré sí Àgbà", sortPriceHigh: "Iye: Àgbà sí Kékeré", sortMostLoved: "Tí A Fẹ́ Jùlọ",
    noItemsFound: "Kò sí aṣọ", searchItems: "Wà àwọn aṣọ...",
  },
  fr: {
    home: "Accueil", about: "À Propos", marketplace: "Boutique", contact: "Contact",
    exploreCollection: "Explorer la Collection", bookFitting: "Prendre Rendez-vous",
    tagline: "Là où le Patrimoine Rencontre la Haute Couture", tagline2: "Habillée pour Chaque Moment Inoubliable",
    tagline3: "Confectionné à la Perfection, Porté avec Fierté", tagline4: "Le Style Africain Moderne Redéfini", tagline5: "Chaque Point Raconte une Histoire",
    newCollection: "Nouvelle Collection", collection: "Collection", newSeason: "Nouvelle Saison",
    featuredPieces: "Pièces Vedettes",
    featuredDesc: "Sélectionnées individuellement depuis notre atelier actuel — chaque pièce est une convergence de culture, de couture et d'art contemporain.",
    shopByCategory: "Acheter par Catégorie", viewCollection: "Voir la Collection Complète",
    ourStory: "Notre Histoire", readMore: "Lire Plus",
    aboutHeading: "À Propos d'O.V Styles",
    aboutP1: "O.V Styles est une maison de mode basée à Lagos, dédiée à la création de vêtements d'une élégance durable — des pièces qui honorent le patrimoine africain tout en commandant l'attention mondiale.",
    aboutP2: "Des commissions bespoke intimement taillées aux collections prêt-à-porter, notre atelier est devenu un nom de confiance parmi les clients avertis à travers le Nigeria et la diaspora.",
    yearsLabel: "Années", designsLabel: "Créations", clientsLabel: "Clients",
    theVisionary: "Le Visionnaire", meetDirector: "Rencontrez le Directeur Créatif",
    ceoTitle: "Directeur Créatif", ceoSubtitle: "O.V Styles · Lagos, Nigeria",
    mindBehind: "L'Esprit Derrière la Marque", codeAndCouture: "Où le Code Rencontre la Couture",
    ceoBio1: "La force créative derrière O.V Styles est une race rare — un visionnaire de la mode qui est aussi à l'aise pour écrire une architecture backend que pour esquisser une silhouette en soie.",
    ceoBio2: "Sa double maîtrise permet à O.V Styles d'opérer à l'intersection de la tradition et de la technologie — où la couture artisanale rencontre l'intelligence de conception basée sur les données.",
    tagHauteCouture: "Haute Couture", tagTechDesign: "Design Technologique", tagAfricanLuxury: "Luxe Africain",
    fullStory: "Histoire Complète",
    whatWeStandFor: "Ce Que Nous Défendons", ourValues: "Nos Valeurs",
    val1Title: "Savoir-faire", val1Desc: "Chaque vêtement est fini à la main avec une précision chirurgicale — où aucun détail n'est trop petit.",
    val2Title: "Patrimoine", val2Desc: "Enraciné dans la richesse de la tradition textile africaine, chaque création relie l'art ancestral à la sophistication moderne.",
    val3Title: "Exclusivité", val3Desc: "Des tirages strictement limités garantissent que chaque client porte quelque chose de véritablement unique.",
    howItWorks: "Comment Ça Fonctionne", bespokeProcess: "Le Processus Bespoke",
    step1Title: "Consultation", step1Desc: "Nous commençons par une conversation approfondie — explorant votre vision, occasion et déclaration.",
    step2Title: "Conception", step2Desc: "Notre équipe créative traduit votre intention en esquisses détaillées.",
    step3Title: "Confection", step3Desc: "Les maîtres tailleurs donnent vie à chaque design en utilisant des matériaux premium.",
    step4Title: "Livraison", step4Desc: "La pièce terminée est livrée avec une séance d'essayage finale — garantissant un résultat impeccable.",
    clientLove: "Amour des Clients", whatTheySay: "Ce Qu'ils Disent",
    t1Quote: "O.V Styles m'a habillée pour mon mariage et je me suis sentie comme une reine. L'artisanat est inégalé.",
    t1Name: "Amara O.", t1Title: "Mariée · Lagos",
    t2Quote: "J'ai porté des marques de luxe internationales, mais rien ne rivalise avec la touche personnelle d'O.V Styles.",
    t2Name: "Chidinma E.", t2Title: "Personnalité TV · Abuja",
    t3Quote: "Chaque pièce porte une histoire. Je reçois des compliments sans exception chaque fois que je porte leurs créations.",
    t3Name: "Fatima B.", t3Title: "Entrepreneuse · Kano",
    discoverLatest: "Découvrir la Dernière Collection",
    discoverText: "Découvrez des pièces exquises confectionnées avec passion et précision pour le connaisseur de mode moderne.",
    shopNow: "Acheter Maintenant",
    newsletterTitle: "Rejoignez le Cercle O.V Styles", newsletterDesc: "Soyez le premier informé des nouvelles collections.",
    emailPlaceholder: "Votre adresse email", subscribe: "S'abonner",
    quickLinks: "Liens Rapides", contactUs: "Contactez-nous", followUs: "Suivez-nous",
    allRights: "Tous droits réservés.", searchPlaceholder: "Rechercher par nom, type...",
    filters: "Filtres", clearFilters: "Effacer", piecesFound: "pièces trouvées",
    category: "Catégorie", color: "Couleur", priceRange: "Gamme de Prix", purchase: "Acheter",
    aboutPageHeroSub: "Né à Lagos. Porté par le monde.", aboutPageEst: "Fondé en 2012",
    theVision: "La Vision", craftingElegance: "Créer l'Élégance Depuis le Premier Jour",
    visionP1: "O.V Styles est né d'une obsession pour la précision et d'un profond respect pour l'identité africaine.",
    visionP2: "Nous ne courons pas après les tendances. Nous créons des vêtements qui survivront à la saison.",
    philosophyLabel: "Philosophie", philosophyHeading: "La Mode avec un Sens",
    philosophyP1: "Nous croyons en un luxe durable, créant de beaux vêtements qui respectent les artisans.",
    philosophyP2: "Notre processus honore la tradition de la haute couture tout en embrassant le design moderne.",
    founderQuote: "Chaque vêtement que nous créons est une lettre d'amour à la culture africaine, écrite en fil et tissu.",
    founderQuoteAttr: "Directeur Créatif, O.V Styles",
    journeyLabel: "Parcours", ourMilestones: "Nos Jalons",
    m1: "O.V Styles fondé à Lagos, Nigeria", m2: "Première présentation à Lagos Fashion Week",
    m3: "Habillé une célébrité pour une grande cérémonie", m4: "Expansion et commandes internationales",
    m5: "Lancement de la collection prêt-à-porter en ligne", m6: "500+ pièces bespoke, 50+ clients distingués",
    directorLabel: "Le Directeur Créatif", directorHeading: "L'Architecte d'O.V Styles",
    directorFullBio1: "L'esprit derrière O.V Styles unit deux domaines: la mode et l'ingénierie logicielle.",
    directorFullBio2: "Il a conçu O.V Styles non seulement comme une maison de mode, mais comme une opération créative de précision.",
    directorFullBio3: "Sa vision est simple: le luxe africain ne devrait pas être une aspiration. Il devrait être la norme.",
    aboutVal1Title: "Savoir-faire", aboutVal1Desc: "Chaque pièce est finie à la main avec une précision méticuleuse.",
    aboutVal2Title: "Élégance", aboutVal2Desc: "Nos créations incarnent une élégance intemporelle.",
    aboutVal3Title: "Patrimoine", aboutVal3Desc: "Nous célébrons le patrimoine africain à travers le design moderne.",
    workWithUs: "Travaillez Avec Nous", createSomething: "Créons Quelque Chose d'Extraordinaire",
    createDesc: "Que vous commandiez une pièce sur mesure ou exploriez la collection, nous accueillons chaque conversation.",
    shopCollection: "Acheter la Collection", getInTouch: "Nous Contacter",
    contactPageHeroSub: "Nous serions ravis d'avoir de vos nouvelles.", contactPageEst: "Lagos, Nigeria",
    getInTouchHeading: "Nous Contacter", getInTouchDesc: "Que vous commandiez une pièce sur mesure, preniez rendez-vous ou souhaitiez simplement en savoir plus sur notre travail, contactez-nous et nous répondrons dans les 24 heures.",
    sendMessage: "Envoyer un Message", messageSent: "Message Reçu",
    messageSentDesc: "Merci de nous avoir contactés. Nous vous répondrons dans les 24 heures.",
    formName: "Nom Complet", formEmail: "Adresse Email", formPhone: "Numéro de Téléphone",
    formSubject: "Sujet", formMessage: "Votre Message",
    formNamePlaceholder: "Votre nom complet", formEmailPlaceholder: "votre@email.com",
    formPhonePlaceholder: "+234 800 000 0000", formSubjectPlaceholder: "Comment pouvons-nous vous aider?",
    formMessagePlaceholder: "Parlez-nous de votre occasion, de la pièce que vous avez en tête...",
    formSending: "Envoi en cours...", formSend: "Envoyer le Message",
    formSubjectOpt1: "Commission Bespoke", formSubjectOpt2: "Réserver un Essayage",
    formSubjectOpt3: "Renseignement Général", formSubjectOpt4: "Partenariat / Presse",
    visitUs: "Visiter l'Atelier", callUs: "Appelez-nous", emailUs: "Envoyez-nous un Email",
    hoursLabel: "Heures d'Atelier", hoursValue: "Lun – Sam, 9h – 18h WAT",
    whatsappUs: "Message WhatsApp", whatsappDesc: "Préférez une réponse plus rapide? Envoyez-nous un message directement sur WhatsApp.",
    messageOnWhatsapp: "Ouvrir WhatsApp",
    faqLabel: "FAQ", faqHeading: "Questions Fréquentes",
    faq1Q: "Combien de temps prend une pièce sur mesure?", faq1A: "Les commissions bespoke prennent généralement entre 2 et 6 semaines selon la complexité.",
    faq2Q: "Proposez-vous des pièces prêt-à-porter?", faq2A: "Oui. Notre collection prêt-à-porter est disponible en éditions strictement limitées.",
    faq3Q: "Puis-je réserver un essayage avant de m'engager?", faq3A: "Absolument. Nous encourageons une consultation initiale avant tout engagement.",
    faq4Q: "Livrez-vous à l'international?", faq4A: "Oui, nous livrons au Nigeria et à l'international. Les délais et coûts seront confirmés à la commande.",
    addToCart: "Ajouter au Panier", addedToCart: "Ajouté", removeFromCart: "Retirer",
    cart: "Panier", cartEmpty: "Votre panier est vide", cartEmptyDesc: "Parcourez la collection et ajoutez des pièces.",
    cartTotal: "Total", checkoutWhatsapp: "Commander via WhatsApp", continueShopping: "Continuer les Achats",
    qty: "Qté", itemsInCart: "articles dans le panier", clearCart: "Vider le Panier",
    loved: "Aimé", loves: "aiment", itemLoved: "Vous aimez cette pièce",
    filterAll: "Tous", sortBy: "Trier par", sortNewest: "Plus récent", sortPriceLow: "Prix: Croissant", sortPriceHigh: "Prix: Décroissant", sortMostLoved: "Plus Aimé",
    noItemsFound: "Aucune pièce trouvée", searchItems: "Rechercher des pièces...",
  },
  ar: {
    home: "الرئيسية", about: "من نحن", marketplace: "المتجر", contact: "اتصل بنا",
    exploreCollection: "استكشف المجموعة", bookFitting: "احجز موعداً",
    tagline: "حيث يلتقي التراث بالأزياء الراقية", tagline2: "مصممة لكل لحظة لا تُنسى",
    tagline3: "مصنوعة بإتقان، تُرتدى بفخر", tagline4: "الأناقة الأفريقية الحديثة", tagline5: "كل غرزة تحكي قصة",
    newCollection: "مجموعة جديدة", collection: "مجموعة", newSeason: "موسم جديد",
    featuredPieces: "القطع المميزة",
    featuredDesc: "مختارة بعناية من أتيليه الحالي — كل قطعة تجمع بين الثقافة والأزياء الراقية والفن المعاصر.",
    shopByCategory: "تسوق حسب الفئة", viewCollection: "عرض المجموعة الكاملة",
    ourStory: "قصتنا", readMore: "اقرأ المزيد",
    aboutHeading: "عن O.V Styles",
    aboutP1: "O.V Styles دار أزياء مقرها لاغوس مكرسة لإنتاج ملابس ذات أناقة دائمة — قطع تُكرّم التراث الأفريقي بينما تجذب الاهتمام العالمي.",
    aboutP2: "من الطلبات المفصلة الخاصة إلى مجموعات الملابس الجاهزة، أصبح أتيليه اسماً موثوقاً بين العملاء المميزين في نيجيريا والشتات.",
    yearsLabel: "سنوات", designsLabel: "تصاميم", clientsLabel: "عملاء",
    theVisionary: "صاحب الرؤية", meetDirector: "تعرف على المدير الإبداعي",
    ceoTitle: "المدير الإبداعي", ceoSubtitle: "O.V Styles · لاغوس، نيجيريا",
    mindBehind: "العقل وراء العلامة", codeAndCouture: "حيث يلتقي الكود بالأزياء",
    ceoBio1: "القوة الإبداعية وراء O.V Styles نوع نادر — رائد أزياء يتقن كتابة بنية الخادم الخلفي بنفس القدر الذي يرسم فيه صورة الحرير.",
    ceoBio2: "إتقانه المزدوج يسمح لـ O.V Styles بالعمل عند تقاطع التقليد والتكنولوجيا — حيث يلتقي الخياطة اليدوية بذكاء التصميم.",
    tagHauteCouture: "أزياء راقية", tagTechDesign: "تصميم تقني", tagAfricanLuxury: "فخامة أفريقية",
    fullStory: "القصة الكاملة",
    whatWeStandFor: "ما نؤمن به", ourValues: "قيمنا",
    val1Title: "الحرفية", val1Desc: "كل ثوب ينتهي باليد بدقة جراحية — حيث لا يوجد تفصيل صغير جداً.",
    val2Title: "التراث", val2Desc: "متجذر في ثراء تقليد النسيج الأفريقي، يجمع كل تصميم بين الفن الأصيل والتطور الحديث.",
    val3Title: "الحصرية", val3Desc: "إنتاج محدود صارم يضمن أن كل عميل يرتدي شيئاً حقيقياً فريداً.",
    howItWorks: "كيف يعمل", bespokeProcess: "عملية التفصيل",
    step1Title: "استشارة", step1Desc: "نبدأ بمحادثة معمقة — نستكشف رؤيتك ومناسبتك والبيان الذي تريد تقديمه.",
    step2Title: "تصميم", step2Desc: "يترجم فريقنا الإبداعي نيتك إلى رسوم تفصيلية.",
    step3Title: "الحرفة", step3Desc: "يجسد الخياطون المهرة كل تصميم باستخدام مواد فاخرة.",
    step4Title: "التسليم", step4Desc: "تُسلَّم القطعة المكتملة مع جلسة قياس نهائية لضمان نتيجة مثالية.",
    clientLove: "حب العملاء", whatTheySay: "ما يقولونه",
    t1Quote: "O.V Styles ألبستني لحفل زفافي وشعرت بأنني ملكة. مستوى الحرفية لا مثيل له.",
    t1Name: "أمارا أو.", t1Title: "عروس · لاغوس",
    t2Quote: "ارتديت علامات فاخرة دولية، لكن لا شيء يضاهي اللمسة الشخصية وجودة O.V Styles.",
    t2Name: "شيدينما إي.", t2Title: "شخصية تلفزيونية · أبوجا",
    t3Quote: "كل قطعة تحمل قصة. أتلقى المجاملات دون استثناء في كل مرة أرتدي تصاميمهم.",
    t3Name: "فاطمة ب.", t3Title: "رائدة أعمال · كانو",
    discoverLatest: "اكتشف أحدث المجموعات",
    discoverText: "اكتشف قطعاً رائعة مصنوعة بشغف ودقة للمعجب بالأزياء الحديثة.",
    shopNow: "تسوق الآن",
    newsletterTitle: "انضم إلى دائرة O.V Styles", newsletterDesc: "كن أول من يعرف عن المجموعات الجديدة.",
    emailPlaceholder: "عنوان بريدك الإلكتروني", subscribe: "اشترك",
    quickLinks: "روابط سريعة", contactUs: "اتصل بنا", followUs: "تابعنا",
    allRights: "جميع الحقوق محفوظة.", searchPlaceholder: "ابحث بالاسم أو النوع...",
    filters: "تصفية", clearFilters: "مسح الفلاتر", piecesFound: "قطعة وجدت",
    category: "الفئة", color: "اللون", priceRange: "نطاق السعر", purchase: "شراء",
    aboutPageHeroSub: "وُلدت في لاغوس. يُرتدى في العالم.", aboutPageEst: "تأسست 2012",
    theVision: "الرؤية", craftingElegance: "صياغة الأناقة منذ اليوم الأول",
    visionP1: "وُلدت O.V Styles من هوس بالدقة واحترام عميق للهوية الأفريقية.",
    visionP2: "نحن لا نلاحق الاتجاهات. نصنع ملابس ستتجاوز الموسم الذي وُلدت فيه.",
    philosophyLabel: "الفلسفة", philosophyHeading: "الموضة بهدف",
    philosophyP1: "نؤمن بالرفاهية المستدامة، خلق ملابس جميلة تحترم الحرفيين.",
    philosophyP2: "من مصادر الأقمشة الفاخرة إلى التفاصيل المنتهية يدوياً، تكرّم عمليتنا تقليد الأزياء الراقية.",
    founderQuote: "كل قطعة نصنعها هي رسالة حب للثقافة الأفريقية، مكتوبة بالخيط والقماش.",
    founderQuoteAttr: "المدير الإبداعي، O.V Styles",
    journeyLabel: "الرحلة", ourMilestones: "معالمنا",
    m1: "تأسست O.V Styles في لاغوس، نيجيريا", m2: "أول عرض في أسبوع الموضة بلاغوس",
    m3: "ألبست مشهوراً لأول مرة لحفل كبير", m4: "التوسع وبدء الطلبات الدولية",
    m5: "إطلاق مجموعة الملابس الجاهزة عبر الإنترنت", m6: "500+ قطعة bespoke، 50+ عميل مميز",
    directorLabel: "المدير الإبداعي", directorHeading: "مهندس O.V Styles",
    directorFullBio1: "العقل وراء O.V Styles يجمع مجالين: الأزياء وهندسة البرمجيات.",
    directorFullBio2: "صمّم O.V Styles ليس فقط كدار أزياء بل كعملية إبداعية دقيقة.",
    directorFullBio3: "رؤيته بسيطة: الرفاهية الأفريقية لا ينبغي أن تكون طموحاً. يجب أن تكون المعيار.",
    aboutVal1Title: "الحرفية", aboutVal1Desc: "كل قطعة تُنهى يدوياً بدقة متناهية.",
    aboutVal2Title: "الأناقة", aboutVal2Desc: "تجسد تصاميمنا أناقة خالدة.",
    aboutVal3Title: "التراث", aboutVal3Desc: "نحتفل بالتراث الأفريقي من خلال التصميم الحديث.",
    workWithUs: "اعمل معنا", createSomething: "لنبتكر شيئاً استثنائياً",
    createDesc: "سواء كنت تطلب قطعة مخصصة أو تستكشف المجموعة، نرحب بكل محادثة.",
    shopCollection: "تسوق المجموعة", getInTouch: "تواصل معنا",
    contactPageHeroSub: "يسعدنا سماع منك.", contactPageEst: "لاغوس، نيجيريا",
    getInTouchHeading: "تواصل معنا", getInTouchDesc: "سواء كنت تطلب قطعة مخصصة أو تحجز موعد قياس أو تريد معرفة المزيد عن عملنا، تواصل معنا وسنرد في غضون 24 ساعة.",
    sendMessage: "إرسال رسالة", messageSent: "تم استلام الرسالة",
    messageSentDesc: "شكراً لتواصلك معنا. سنرد عليك في غضون 24 ساعة.",
    formName: "الاسم الكامل", formEmail: "عنوان البريد الإلكتروني", formPhone: "رقم الهاتف",
    formSubject: "الموضوع", formMessage: "رسالتك",
    formNamePlaceholder: "اسمك الكامل", formEmailPlaceholder: "بريدك@الإلكتروني.com",
    formPhonePlaceholder: "+234 800 000 0000", formSubjectPlaceholder: "كيف يمكننا مساعدتك؟",
    formMessagePlaceholder: "أخبرنا عن مناسبتك أو القطعة التي تفكر فيها...",
    formSending: "جارٍ الإرسال...", formSend: "إرسال الرسالة",
    formSubjectOpt1: "طلب مخصص", formSubjectOpt2: "حجز موعد قياس",
    formSubjectOpt3: "استفسار عام", formSubjectOpt4: "شراكة / صحافة",
    visitUs: "زيارة الأتيليه", callUs: "اتصل بنا", emailUs: "راسلنا",
    hoursLabel: "ساعات الأتيليه", hoursValue: "الاثنين – السبت، 9ص – 6م WAT",
    whatsappUs: "رسالة واتساب", whatsappDesc: "تفضل رداً أسرع؟ أرسل لنا رسالة مباشرة على واتساب.",
    messageOnWhatsapp: "فتح واتساب",
    faqLabel: "أسئلة شائعة", faqHeading: "الأسئلة الشائعة",
    faq1Q: "كم من الوقت تستغرق القطعة المخصصة؟", faq1A: "تستغرق الطلبات المخصصة عادةً من 2 إلى 6 أسابيع حسب تعقيد التصميم.",
    faq2Q: "هل تقدمون ملابس جاهزة؟", faq2A: "نعم. مجموعتنا الجاهزة متاحة بإصدارات محدودة للغاية.",
    faq3Q: "هل يمكنني حجز موعد قياس قبل الالتزام؟", faq3A: "بالتأكيد. نشجع على استشارة أولية قبل أي التزام.",
    faq4Q: "هل تشحنون دولياً؟", faq4A: "نعم، نوصل إلى نيجيريا وعالمياً. سيتم تأكيد المواعيد والتكاليف عند الطلب.",
    addToCart: "أضف إلى السلة", addedToCart: "أُضيف", removeFromCart: "إزالة",
    cart: "السلة", cartEmpty: "سلتك فارغة", cartEmptyDesc: "تصفح المجموعة وأضف القطع التي تعجبك.",
    cartTotal: "الإجمالي", checkoutWhatsapp: "الدفع عبر WhatsApp", continueShopping: "مواصلة التسوق",
    qty: "الكمية", itemsInCart: "عناصر في السلة", clearCart: "إفراغ السلة",
    loved: "محبوب", loves: "يحبون", itemLoved: "أعجبتك هذه القطعة",
    filterAll: "الكل", sortBy: "ترتيب حسب", sortNewest: "الأحدث", sortPriceLow: "السعر: الأدنى أولاً", sortPriceHigh: "السعر: الأعلى أولاً", sortMostLoved: "الأكثر إعجاباً",
    noItemsFound: "لم يتم العثور على قطع", searchItems: "ابحث عن قطع...",
  },
  ru: {
    home: "Главная", about: "О нас", marketplace: "Магазин", contact: "Контакты",
    exploreCollection: "Смотреть коллекцию", bookFitting: "Записаться на примерку",
    tagline: "Где наследие встречает высокую моду", tagline2: "Одета для каждого незабываемого момента",
    tagline3: "Создано с совершенством, носится с гордостью", tagline4: "Современный африканский стиль", tagline5: "Каждый стежок рассказывает историю",
    newCollection: "Новая коллекция", collection: "Коллекция", newSeason: "Новый сезон",
    featuredPieces: "Избранные изделия",
    featuredDesc: "Индивидуально отобраны из нашего текущего ателье — каждое изделие является сочетанием культуры, моды и современного искусства.",
    shopByCategory: "Покупки по категориям", viewCollection: "Вся коллекция",
    ourStory: "Наша история", readMore: "Читать далее",
    aboutHeading: "О компании O.V Styles",
    aboutP1: "O.V Styles — модный дом, расположенный в Лагосе, посвящённый созданию одежды неизменной элегантности — изделий, чтящих африканское наследие и привлекающих мировое внимание.",
    aboutP2: "От индивидуально пошитых bespoke заказов до коллекций прêt-à-porter, наше ателье стало надёжным именем среди взыскательных клиентов по всей Нигерии и диаспоре.",
    yearsLabel: "Лет", designsLabel: "Дизайнов", clientsLabel: "Клиентов",
    theVisionary: "Визионер", meetDirector: "Познакомьтесь с креативным директором",
    ceoTitle: "Креативный директор", ceoSubtitle: "O.V Styles · Лагос, Нигерия",
    mindBehind: "Разум за брендом", codeAndCouture: "Там, где код встречает кутюр",
    ceoBio1: "Творческая сила за O.V Styles — редкий тип: модный визионер, одинаково свободно пишущий backend-архитектуру и рисующий шёлковый силуэт.",
    ceoBio2: "Его двойное мастерство позволяет O.V Styles работать на пересечении традиции и технологий — где ручной пошив встречается с интеллектом дизайна.",
    tagHauteCouture: "Высокая мода", tagTechDesign: "Технологический дизайн", tagAfricanLuxury: "Африканская роскошь",
    fullStory: "Полная история",
    whatWeStandFor: "Наши принципы", ourValues: "Наши ценности",
    val1Title: "Мастерство", val1Desc: "Каждое изделие отделывается вручную с хирургической точностью — здесь нет слишком мелких деталей.",
    val2Title: "Наследие", val2Desc: "Укоренённый в богатстве африканских текстильных традиций, каждый дизайн соединяет родовое искусство с современной изысканностью.",
    val3Title: "Эксклюзивность", val3Desc: "Строго ограниченные тиражи гарантируют, что каждый клиент носит нечто подлинно уникальное.",
    howItWorks: "Как это работает", bespokeProcess: "Bespoke процесс",
    step1Title: "Консультация", step1Desc: "Мы начинаем с глубокой беседы — изучая вашу vision, повод и послание, которое вы хотите донести.",
    step2Title: "Дизайн", step2Desc: "Наша творческая команда переводит ваш замысел в детальные эскизы.",
    step3Title: "Пошив", step3Desc: "Мастера-портные воплощают каждый дизайн в жизнь, используя премиальные материалы.",
    step4Title: "Доставка", step4Desc: "Готовое изделие доставляется с финальной примеркой — для безупречного результата.",
    clientLove: "Любовь клиентов", whatTheySay: "Что они говорят",
    t1Quote: "O.V Styles одели меня на свадьбу, и я чувствовала себя королевой. Мастерство несравненно нигде в Лагосе.",
    t1Name: "Амара О.", t1Title: "Невеста · Лагос",
    t2Quote: "Я носила международные люксовые бренды, но ничто не сравнится с личным прикосновением и качеством O.V Styles.",
    t2Name: "Чидинма Э.", t2Title: "ТВ-личность · Абуджа",
    t3Quote: "Каждое изделие несёт историю. Я получаю комплименты без исключения каждый раз, когда выхожу в их дизайнах.",
    t3Name: "Фатима Б.", t3Title: "Предприниматель · Кано",
    discoverLatest: "Откройте последнюю коллекцию",
    discoverText: "Откройте для себя изысканные изделия, созданные с страстью и точностью для ценителя современной моды.",
    shopNow: "Купить сейчас",
    newsletterTitle: "Присоединяйтесь к O.V Styles", newsletterDesc: "Будьте первым, кто узнает о новых коллекциях.",
    emailPlaceholder: "Ваш email адрес", subscribe: "Подписаться",
    quickLinks: "Быстрые ссылки", contactUs: "Связаться с нами", followUs: "Подписаться",
    allRights: "Все права защищены.", searchPlaceholder: "Поиск по названию, типу...",
    filters: "Фильтры", clearFilters: "Сбросить фильтры", piecesFound: "изделий найдено",
    category: "Категория", color: "Цвет", priceRange: "Диапазон цен", purchase: "Купить",
    aboutPageHeroSub: "Рождён в Лагосе. Носят по всему миру.", aboutPageEst: "Основан в 2012",
    theVision: "Видение", craftingElegance: "Создание элегантности с первого дня",
    visionP1: "O.V Styles родился из одержимости точностью и глубокого уважения к африканской идентичности.",
    visionP2: "Мы не гонимся за трендами. Мы создаём одежду, которая переживёт сезон.",
    philosophyLabel: "Философия", philosophyHeading: "Мода с Целью",
    philosophyP1: "Мы верим в устойчивую роскошь, создавая красивые изделия, которые уважают мастеров.",
    philosophyP2: "Наш процесс чтит традицию высокой моды, принимая современный дизайн.",
    founderQuote: "Каждое изделие, которое мы создаём, — это любовное письмо африканской культуре, написанное нитью и тканью.",
    founderQuoteAttr: "Креативный директор, O.V Styles",
    journeyLabel: "Путь", ourMilestones: "Наши Достижения",
    m1: "O.V Styles основан в Лагосе, Нигерия", m2: "Первый показ на Неделе моды в Лагосе",
    m3: "Одели знаменитость для крупной церемонии", m4: "Расширение и международные заказы",
    m5: "Запуск коллекции прêт-à-porter онлайн", m6: "500+ bespoke изделий, 50+ выдающихся клиентов",
    directorLabel: "Креативный директор", directorHeading: "Архитектор O.V Styles",
    directorFullBio1: "Разум за O.V Styles объединяет две области: моду и программную инженерию.",
    directorFullBio2: "Он спроектировал O.V Styles не просто как модный дом, но как творческую операцию точности.",
    directorFullBio3: "Его видение простое: африканская роскошь не должна быть стремлением. Она должна быть стандартом.",
    aboutVal1Title: "Мастерство", aboutVal1Desc: "Каждое изделие отделывается вручную с точностью.",
    aboutVal2Title: "Элегантность", aboutVal2Desc: "Наши дизайны воплощают вневременную элегантность.",
    aboutVal3Title: "Наследие", aboutVal3Desc: "Мы отмечаем африканское наследие через современный дизайн.",
    workWithUs: "Работайте с нами", createSomething: "Создадим Что-то Исключительное",
    createDesc: "Будь то заказ bespoke или исследование коллекции, мы рады каждому разговору.",
    shopCollection: "Купить Коллекцию", getInTouch: "Связаться",
    contactPageHeroSub: "Нам будет приятно получить от вас весточку.", contactPageEst: "Лагос, Нигерия",
    getInTouchHeading: "Свяжитесь с нами", getInTouchDesc: "Будь то заказ bespoke, примерка или просто вопрос о нашей работе, свяжитесь с нами и мы ответим в течение 24 часов.",
    sendMessage: "Отправить сообщение", messageSent: "Сообщение получено",
    messageSentDesc: "Спасибо за обращение. Мы свяжемся с вами в течение 24 часов.",
    formName: "Полное имя", formEmail: "Адрес электронной почты", formPhone: "Номер телефона",
    formSubject: "Тема", formMessage: "Ваше сообщение",
    formNamePlaceholder: "Ваше полное имя", formEmailPlaceholder: "ваш@email.com",
    formPhonePlaceholder: "+234 800 000 0000", formSubjectPlaceholder: "Как мы можем помочь?",
    formMessagePlaceholder: "Расскажите нам о вашем событии или изделии, которое вы имеете в виду...",
    formSending: "Отправка...", formSend: "Отправить сообщение",
    formSubjectOpt1: "Bespoke заказ", formSubjectOpt2: "Записаться на примерку",
    formSubjectOpt3: "Общий вопрос", formSubjectOpt4: "Партнёрство / Пресса",
    visitUs: "Посетить Ателье", callUs: "Позвоните нам", emailUs: "Написать на email",
    hoursLabel: "Часы работы", hoursValue: "Пн – Сб, 9:00 – 18:00 WAT",
    whatsappUs: "Написать в WhatsApp", whatsappDesc: "Предпочитаете быстрый ответ? Напишите нам напрямую в WhatsApp.",
    messageOnWhatsapp: "Открыть WhatsApp",
    faqLabel: "FAQ", faqHeading: "Частые вопросы",
    faq1Q: "Сколько времени занимает bespoke изделие?", faq1A: "Bespoke заказы обычно занимают от 2 до 6 недель в зависимости от сложности дизайна.",
    faq2Q: "Есть ли у вас изделия прêт-à-porter?", faq2A: "Да. Наша коллекция прêт-à-porter доступна в строго ограниченных тиражах.",
    faq3Q: "Могу ли я записаться на примерку перед заказом?", faq3A: "Конечно. Мы рекомендуем начальную консультацию перед любым обязательством.",
    faq4Q: "Доставляете ли вы международно?", faq4A: "Да, мы доставляем по Нигерии и за рубеж. Сроки и стоимость будут подтверждены при оформлении заказа.",
    addToCart: "В корзину", addedToCart: "Добавлено", removeFromCart: "Убрать",
    cart: "Корзина", cartEmpty: "Ваша корзина пуста", cartEmptyDesc: "Просматривайте коллекцию и добавляйте понравившиеся изделия.",
    cartTotal: "Итого", checkoutWhatsapp: "Оформить через WhatsApp", continueShopping: "Продолжить покупки",
    qty: "Кол-во", itemsInCart: "товаров в корзине", clearCart: "Очистить корзину",
    loved: "Нравится", loves: "нравится", itemLoved: "Вам понравилось это изделие",
    filterAll: "Все", sortBy: "Сортировать", sortNewest: "Новинки", sortPriceLow: "Цена: по возрастанию", sortPriceHigh: "Цена: по убыванию", sortMostLoved: "Самые популярные",
    noItemsFound: "Изделия не найдены", searchItems: "Поиск изделий...",
  },
  zh: {
    home: "首页", about: "关于我们", marketplace: "购物", contact: "联系我们",
    exploreCollection: "探索系列", bookFitting: "预约试穿",
    tagline: "传承与高级定制的交汇", tagline2: "为每个难忘时刻而着装",
    tagline3: "精心制作，自豪穿戴", tagline4: "重新定义现代非洲风尚", tagline5: "每一针都讲述一个故事",
    newCollection: "新系列", collection: "系列", newSeason: "新季节",
    featuredPieces: "精选单品",
    featuredDesc: "从我们当前工作室精心挑选——每件作品都是文化、高级定制和当代艺术的融合。",
    shopByCategory: "按类别购物", viewCollection: "查看完整系列",
    ourStory: "我们的故事", readMore: "阅读更多",
    aboutHeading: "关于O.V Styles",
    aboutP1: "O.V Styles是一家总部位于拉各斯的时装屋，致力于打造经久不衰的优雅服装——这些作品尊重非洲遗产，同时吸引全球关注。",
    aboutP2: "从精心定制的私人定制到精心策划的成衣系列，我们的工作室已成为尼日利亚及海外挑剔客户信赖的名字。",
    yearsLabel: "年", designsLabel: "设计", clientsLabel: "客户",
    theVisionary: "远见者", meetDirector: "认识创意总监",
    ceoTitle: "创意总监", ceoSubtitle: "O.V Styles · 拉各斯，尼日利亚",
    mindBehind: "品牌背后的智慧", codeAndCouture: "代码与时装的交汇",
    ceoBio1: "O.V Styles背后的创意力量是一种罕见的人才——一位时尚远见者，在编写后端架构和勾勒丝绸轮廓方面同样得心应手。",
    ceoBio2: "他的双重掌握使O.V Styles能够在传统与技术的交汇处运作——手工剪裁与数据驱动设计智能相遇。",
    tagHauteCouture: "高级定制", tagTechDesign: "科技驱动设计", tagAfricanLuxury: "非洲奢华",
    fullStory: "完整故事",
    whatWeStandFor: "我们的立场", ourValues: "我们的价值观",
    val1Title: "工艺", val1Desc: "每件衣服都以外科手术般的精确度手工完成——没有任何细节太小。",
    val2Title: "传承", val2Desc: "植根于非洲纺织传统的丰富，每个设计将祖先艺术与现代精致联系起来。",
    val3Title: "独特性", val3Desc: "严格限量生产确保每位客户都能穿上真正独一无二的作品。",
    howItWorks: "如何运作", bespokeProcess: "定制流程",
    step1Title: "咨询", step1Desc: "我们从深入对话开始——探索您的愿景、场合和您希望传达的声明。",
    step2Title: "设计", step2Desc: "我们的创意团队将您的意图转化为详细的草图。",
    step3Title: "制作", step3Desc: "大师裁缝使用优质材料将每个设计变为现实。",
    step4Title: "交付", step4Desc: "完成的作品连同最终试装会一起交付——确保完美无瑕的结果。",
    clientLove: "客户之爱", whatTheySay: "他们说什么",
    t1Quote: "O.V Styles为我的婚礼设计了礼服，我感觉自己像女王。工艺水平在拉各斯无与伦比。",
    t1Name: "阿玛拉·O.", t1Title: "新娘 · 拉各斯",
    t2Quote: "我穿过国际奢侈品牌，但没有什么能与O.V Styles的个人风格和质量相媲美。",
    t2Name: "奇迪姆马·E.", t2Title: "电视名人 · 阿布贾",
    t3Quote: "每件作品都承载着一个故事。每次穿上他们的设计出门，我都会毫无例外地收到赞美。",
    t3Name: "法蒂玛·B.", t3Title: "企业家 · 卡诺",
    discoverLatest: "探索最新系列",
    discoverText: "探索用激情和精准工艺制作的精美单品，专为现代时尚鉴赏家打造。",
    shopNow: "立即购买",
    newsletterTitle: "加入O.V Styles圈子", newsletterDesc: "第一时间了解新系列和独家活动。",
    emailPlaceholder: "您的电子邮件地址", subscribe: "订阅",
    quickLinks: "快速链接", contactUs: "联系我们", followUs: "关注我们",
    allRights: "版权所有。", searchPlaceholder: "按名称、类型搜索...",
    filters: "筛选", clearFilters: "清除筛选", piecesFound: "件商品",
    category: "类别", color: "颜色", priceRange: "价格范围", purchase: "购买",
    aboutPageHeroSub: "诞生于拉各斯，被世界穿着。", aboutPageEst: "成立于2012年",
    theVision: "愿景", craftingElegance: "从第一天起就打造优雅",
    visionP1: "O.V Styles诞生于对精准的执着和对非洲身份的深切尊重。",
    visionP2: "我们不追逐潮流。我们打造能超越诞生季节的服装。",
    philosophyLabel: "理念", philosophyHeading: "有目的的时尚",
    philosophyP1: "我们相信可持续奢华，创造美丽的服装，尊重制作它们的工匠。",
    philosophyP2: "从采购优质面料到最终手工细节，我们的流程尊重高级定制传统。",
    founderQuote: "我们创作的每件服装都是写给非洲文化的情书，用线和布料书写。",
    founderQuoteAttr: "创意总监，O.V Styles",
    journeyLabel: "历程", ourMilestones: "我们的里程碑",
    m1: "O.V Styles在拉各斯，尼日利亚创立", m2: "首次在拉各斯时装周亮相",
    m3: "为名人出席重大颁奖典礼设计礼服", m4: "扩张并开始国际委托",
    m5: "在线推出成衣系列", m6: "500+件定制服装，50+位杰出客户",
    directorLabel: "创意总监", directorHeading: "O.V Styles的架构师",
    directorFullBio1: "O.V Styles背后的智慧融合了两个领域：时装和软件工程。",
    directorFullBio2: "他将O.V Styles设计为不仅是时装屋，而是精密创意运营。",
    directorFullBio3: "他的愿景简单明了：非洲奢华不应该是一种渴望，而应该是标准。",
    aboutVal1Title: "工艺", aboutVal1Desc: "每件作品都以精确的手工完成。",
    aboutVal2Title: "优雅", aboutVal2Desc: "我们的设计体现永恒的优雅。",
    aboutVal3Title: "传承", aboutVal3Desc: "我们通过现代设计庆祝非洲传承。",
    workWithUs: "与我们合作", createSomething: "让我们创造非凡之物",
    createDesc: "无论您是订购定制作品还是探索系列，我们欢迎每次对话。",
    shopCollection: "购买系列", getInTouch: "联系我们",
    contactPageHeroSub: "我们很乐意收到您的来信。", contactPageEst: "拉各斯，尼日利亚",
    getInTouchHeading: "联系我们", getInTouchDesc: "无论您是委托定制、预约试装，还是想了解我们的工作，请联系我们，我们将在24小时内回复。",
    sendMessage: "发送消息", messageSent: "消息已收到",
    messageSentDesc: "感谢您的联系。我们将在24小时内与您取得联系。",
    formName: "全名", formEmail: "电子邮件地址", formPhone: "电话号码",
    formSubject: "主题", formMessage: "您的消息",
    formNamePlaceholder: "您的全名", formEmailPlaceholder: "您的@邮箱.com",
    formPhonePlaceholder: "+234 800 000 0000", formSubjectPlaceholder: "我们能为您做什么？",
    formMessagePlaceholder: "告诉我们您的场合或您心目中的服装...",
    formSending: "发送中...", formSend: "发送消息",
    formSubjectOpt1: "定制委托", formSubjectOpt2: "预约试装",
    formSubjectOpt3: "一般咨询", formSubjectOpt4: "合作 / 媒体",
    visitUs: "参观工作室", callUs: "致电我们", emailUs: "发邮件给我们",
    hoursLabel: "工作室时间", hoursValue: "周一至周六，上午9时至下午6时 WAT",
    whatsappUs: "WhatsApp消息", whatsappDesc: "希望更快得到回复？直接在WhatsApp上给我们发消息。",
    messageOnWhatsapp: "打开WhatsApp",
    faqLabel: "常见问题", faqHeading: "常见问题解答",
    faq1Q: "定制服装需要多长时间？", faq1A: "定制委托通常需要2至6周，具体取决于设计复杂程度。",
    faq2Q: "您提供成衣吗？", faq2A: "是的。我们的精选成衣系列以严格限量版本提供。",
    faq3Q: "我可以在确认前预约试装吗？", faq3A: "当然可以。我们鼓励在做出任何承诺之前进行初步咨询。",
    faq4Q: "您提供国际配送吗？", faq4A: "是的，我们向尼日利亚和国际客户配送。配送时间和费用将在下单时确认。",
    addToCart: "加入购物车", addedToCart: "已加入", removeFromCart: "移除",
    cart: "购物车", cartEmpty: "您的购物车是空的", cartEmptyDesc: "浏览系列并添加您喜欢的单品。",
    cartTotal: "总计", checkoutWhatsapp: "通过WhatsApp结账", continueShopping: "继续购物",
    qty: "数量", itemsInCart: "件商品在购物车中", clearCart: "清空购物车",
    loved: "喜欢", loves: "人喜欢", itemLoved: "您喜欢这件单品",
    filterAll: "全部", sortBy: "排序", sortNewest: "最新", sortPriceLow: "价格：低到高", sortPriceHigh: "价格：高到低", sortMostLoved: "最受欢迎",
    noItemsFound: "未找到单品", searchItems: "搜索单品...",
  },
  hi: {
    home: "होम", about: "हमारे बारे में", marketplace: "दुकान", contact: "संपर्क करें",
    exploreCollection: "संग्रह देखें", bookFitting: "फिटिंग बुक करें",
    tagline: "जहाँ विरासत मिलती है हौट कॉउचर से", tagline2: "हर यादगार पल के लिए तैयार",
    tagline3: "परफेक्शन से बना, गर्व से पहना", tagline4: "आधुनिक अफ्रीकी फैशन, नए सिरे से", tagline5: "हर सिलाई एक कहानी कहती है",
    newCollection: "नया संग्रह", collection: "संग्रह", newSeason: "नया मौसम",
    featuredPieces: "विशेष पीसेस",
    featuredDesc: "हमारे वर्तमान एटेलियर से व्यक्तिगत रूप से चुने गए — प्रत्येक पीस संस्कृति, कॉउचर और समकालीन कला का संगम है।",
    shopByCategory: "श्रेणी के अनुसार खरीदें", viewCollection: "पूरा संग्रह देखें",
    ourStory: "हमारी कहानी", readMore: "और पढ़ें",
    aboutHeading: "O.V Styles के बारे में",
    aboutP1: "O.V Styles लागोस स्थित एक फैशन हाउस है जो स्थायी सुंदरता के वस्त्र बनाने के लिए समर्पित है — ऐसे पीस जो अफ्रीकी विरासत का सम्मान करते हुए वैश्विक ध्यान आकर्षित करते हैं।",
    aboutP2: "व्यक्तिगत बेस्पोक कमीशन से लेकर क्यूरेटेड रेडी-टू-वेयर संग्रह तक, हमारा एटेलियर नाइजीरिया और प्रवासी भारतीयों के बीच विवेकशील ग्राहकों के बीच एक विश्वसनीय नाम बन गया है।",
    yearsLabel: "वर्ष", designsLabel: "डिज़ाइन", clientsLabel: "ग्राहक",
    theVisionary: "दूरदर्शी", meetDirector: "क्रिएटिव डायरेक्टर से मिलें",
    ceoTitle: "क्रिएटिव डायरेक्टर", ceoSubtitle: "O.V Styles · लागोस, नाइजीरिया",
    mindBehind: "ब्रांड के पीछे का दिमाग", codeAndCouture: "जहाँ कोड कॉउचर से मिलता है",
    ceoBio1: "O.V Styles के पीछे की रचनात्मक शक्ति एक दुर्लभ प्रकार है — एक फैशन दूरदर्शी जो बैकएंड आर्किटेक्चर लिखने में उतना ही सहज है जितना सिल्क सिल्हूट स्केच करने में।",
    ceoBio2: "उनकी दोहरी महारत O.V Styles को परंपरा और प्रौद्योगिकी के चौराहे पर काम करने देती है — जहाँ हस्तनिर्मित दर्जी डेटा-संचालित डिज़ाइन बुद्धिमत्ता से मिलती है।",
    tagHauteCouture: "हौट कॉउचर", tagTechDesign: "टेक-संचालित डिज़ाइन", tagAfricanLuxury: "अफ्रीकी विलासिता",
    fullStory: "पूरी कहानी",
    whatWeStandFor: "हम किसके लिए खड़े हैं", ourValues: "हमारे मूल्य",
    val1Title: "शिल्प कौशल", val1Desc: "प्रत्येक वस्त्र को सर्जिकल सटीकता के साथ हाथ से फिनिश किया जाता है।",
    val2Title: "विरासत", val2Desc: "अफ्रीकी वस्त्र परंपरा की समृद्धि में निहित, प्रत्येक डिज़ाइन पूर्वज कला और आधुनिक परिष्कार को जोड़ता है।",
    val3Title: "विशिष्टता", val3Desc: "कड़ाई से सीमित उत्पादन रन यह सुनिश्चित करते हैं कि प्रत्येक ग्राहक कुछ अनूठा पहने।",
    howItWorks: "यह कैसे काम करता है", bespokeProcess: "बेस्पोक प्रक्रिया",
    step1Title: "परामर्श", step1Desc: "हम गहरी बातचीत से शुरू करते हैं — आपकी दृष्टि, अवसर और संदेश की खोज करते हैं।",
    step2Title: "डिज़ाइन", step2Desc: "हमारी क्रिएटिव टीम आपके इरादे को विस्तृत स्केच में अनुवाद करती है।",
    step3Title: "निर्माण", step3Desc: "मास्टर दर्जी प्रीमियम सामग्री का उपयोग करके प्रत्येक डिज़ाइन को जीवंत करते हैं।",
    step4Title: "डिलीवरी", step4Desc: "पूर्ण पीस को अंतिम फिटिंग सत्र के साथ डिलीवर किया जाता है।",
    clientLove: "ग्राहक प्रेम", whatTheySay: "वे क्या कहते हैं",
    t1Quote: "O.V Styles ने मेरी शादी के लिए मुझे तैयार किया और मुझे रानी जैसा महसूस हुआ। शिल्प कौशल बेजोड़ है।",
    t1Name: "अमारा ओ.", t1Title: "दुल्हन · लागोस",
    t2Quote: "मैंने अंतरराष्ट्रीय लग्जरी ब्रांड पहने हैं, लेकिन O.V Styles की व्यक्तिगत स्पर्श और गुणवत्ता की बराबरी कुछ नहीं कर सकता।",
    t2Name: "चिडिनमा ई.", t2Title: "टीवी व्यक्तित्व · अबुजा",
    t3Quote: "प्रत्येक पीस एक कहानी कहता है। जब भी मैं उनके डिज़ाइन में बाहर जाती हूं, मुझे बिना किसी अपवाद के तारीफ मिलती है।",
    t3Name: "फातिमा बी.", t3Title: "उद्यमी · कानो",
    discoverLatest: "नवीनतम संग्रह खोजें",
    discoverText: "आधुनिक फैशन पारखी के लिए जुनून और सटीकता के साथ बने उत्कृष्ट पीस खोजें।",
    shopNow: "अभी खरीदें",
    newsletterTitle: "O.V Styles सर्कल में शामिल हों", newsletterDesc: "नए संग्रह के बारे में सबसे पहले जानें।",
    emailPlaceholder: "आपका ईमेल पता", subscribe: "सदस्यता लें",
    quickLinks: "त्वरित लिंक", contactUs: "संपर्क करें", followUs: "फॉलो करें",
    allRights: "सर्वाधिकार सुरक्षित।", searchPlaceholder: "नाम, प्रकार से खोजें...",
    filters: "फ़िल्टर", clearFilters: "फ़िल्टर साफ़ करें", piecesFound: "पीसेस मिले",
    category: "श्रेणी", color: "रंग", priceRange: "मूल्य सीमा", purchase: "खरीदें",
    aboutPageHeroSub: "लागोस में जन्मा। दुनिया भर में पहना जाता है।", aboutPageEst: "स्थापित 2012",
    theVision: "दृष्टि", craftingElegance: "पहले दिन से सुंदरता का निर्माण",
    visionP1: "O.V Styles सटीकता के प्रति जुनून और अफ्रीकी पहचान के प्रति गहरे सम्मान से जन्मा।",
    visionP2: "हम ट्रेंड का पीछा नहीं करते। हम ऐसे वस्त्र बनाते हैं जो मौसम से परे रहेंगे।",
    philosophyLabel: "दर्शन", philosophyHeading: "उद्देश्य के साथ फैशन",
    philosophyP1: "हम टिकाऊ विलासिता में विश्वास करते हैं, सुंदर वस्त्र बनाते हैं जो कारीगरों का सम्मान करते हैं।",
    philosophyP2: "हमारी प्रक्रिया हौट कॉउचर की परंपरा का सम्मान करती है।",
    founderQuote: "हम जो हर वस्त्र बनाते हैं वह अफ्रीकी संस्कृति को एक प्रेम पत्र है, धागे और कपड़े में लिखा।",
    founderQuoteAttr: "क्रिएटिव डायरेक्टर, O.V Styles",
    journeyLabel: "यात्रा", ourMilestones: "हमारे मील के पत्थर",
    m1: "O.V Styles की स्थापना लागोस, नाइजीरिया में", m2: "लागोस फैशन वीक में पहला शोकेस",
    m3: "किसी बड़े समारोह के लिए पहली बार किसी हस्ती को तैयार किया", m4: "विस्तार और अंतर्राष्ट्रीय कमीशन",
    m5: "ऑनलाइन रेडी-टू-वेयर संग्रह लॉन्च किया", m6: "500+ बेस्पोक पीस, 50+ विशिष्ट ग्राहक",
    directorLabel: "क्रिएटिव डायरेक्टर", directorHeading: "O.V Styles के आर्किटेक्ट",
    directorFullBio1: "O.V Styles के पीछे का दिमाग दो क्षेत्रों को जोड़ता है: फैशन और सॉफ्टवेयर इंजीनियरिंग।",
    directorFullBio2: "उन्होंने O.V Styles को न केवल एक फैशन लेबल के रूप में डिज़ाइन किया बल्कि एक सटीक रचनात्मक संचालन के रूप में।",
    directorFullBio3: "उनका दृष्टिकोण सरल है: अफ्रीकी विलासिता एक आकांक्षा नहीं होनी चाहिए। यह मानक होनी चाहिए।",
    aboutVal1Title: "शिल्प कौशल", aboutVal1Desc: "प्रत्येक पीस को सटीकता के साथ हाथ से फिनिश किया जाता है।",
    aboutVal2Title: "सौंदर्य", aboutVal2Desc: "हमारे डिज़ाइन कालातीत सुंदरता को मूर्त रूप देते हैं।",
    aboutVal3Title: "विरासत", aboutVal3Desc: "हम आधुनिक डिज़ाइन के माध्यम से अफ्रीकी विरासत का जश्न मनाते हैं।",
    workWithUs: "हमारे साथ काम करें", createSomething: "आइए कुछ असाधारण बनाएं",
    createDesc: "चाहे आप बेस्पोक पीस कमीशन कर रहे हों या संग्रह देख रहे हों, हम हर बातचीत का स्वागत करते हैं।",
    shopCollection: "संग्रह खरीदें", getInTouch: "संपर्क करें",
    contactPageHeroSub: "हम आपसे सुनना पसंद करेंगे।", contactPageEst: "लागोस, नाइजीरिया",
    getInTouchHeading: "संपर्क करें", getInTouchDesc: "चाहे आप बेस्पोक पीस कमीशन कर रहे हों, फिटिंग बुक कर रहे हों, या बस हमारे काम के बारे में जिज्ञासु हों, हमसे संपर्क करें और हम 24 घंटे में जवाब देंगे।",
    sendMessage: "संदेश भेजें", messageSent: "संदेश प्राप्त हुआ",
    messageSentDesc: "संपर्क करने के लिए धन्यवाद। हम 24 घंटे में आपसे संपर्क करेंगे।",
    formName: "पूरा नाम", formEmail: "ईमेल पता", formPhone: "फ़ोन नंबर",
    formSubject: "विषय", formMessage: "आपका संदेश",
    formNamePlaceholder: "आपका पूरा नाम", formEmailPlaceholder: "आपका@ईमेल.com",
    formPhonePlaceholder: "+234 800 000 0000", formSubjectPlaceholder: "हम आपकी कैसे मदद कर सकते हैं?",
    formMessagePlaceholder: "हमें अपने अवसर या उस पीस के बारे में बताएं जो आपके मन में है...",
    formSending: "भेज रहे हैं...", formSend: "संदेश भेजें",
    formSubjectOpt1: "बेस्पोक कमीशन", formSubjectOpt2: "फिटिंग बुक करें",
    formSubjectOpt3: "सामान्य पूछताछ", formSubjectOpt4: "साझेदारी / प्रेस",
    visitUs: "एटेलियर आएं", callUs: "हमें कॉल करें", emailUs: "ईमेल करें",
    hoursLabel: "एटेलियर घंटे", hoursValue: "सोम – शनि, सुबह 9 – शाम 6 WAT",
    whatsappUs: "WhatsApp संदेश", whatsappDesc: "तेज़ जवाब चाहते हैं? हमें सीधे WhatsApp पर संदेश भेजें।",
    messageOnWhatsapp: "WhatsApp खोलें",
    faqLabel: "FAQ", faqHeading: "सामान्य प्रश्न",
    faq1Q: "बेस्पोक पीस में कितना समय लगता है?", faq1A: "बेस्पोक कमीशन आमतौर पर डिज़ाइन की जटिलता के आधार पर 2 से 6 सप्ताह लेते हैं।",
    faq2Q: "क्या आप रेडी-टू-वेयर पीस ऑफर करते हैं?", faq2A: "हाँ। हमारी क्यूरेटेड रेडी-टू-वेयर संग्रह सख्त सीमित संस्करणों में उपलब्ध है।",
    faq3Q: "क्या मैं प्रतिबद्ध होने से पहले फिटिंग बुक कर सकता हूं?", faq3A: "बिल्कुल। हम किसी भी प्रतिबद्धता से पहले प्रारंभिक परामर्श को प्रोत्साहित करते हैं।",
    faq4Q: "क्या आप अंतरराष्ट्रीय स्तर पर शिप करते हैं?", faq4A: "हाँ, हम नाइजीरिया और अंतरराष्ट्रीय स्तर पर डिलीवर करते हैं। शिपिंग समय और लागत ऑर्डर पर पुष्टि की जाएगी।",
    addToCart: "कार्ट में जोड़ें", addedToCart: "जोड़ा गया", removeFromCart: "हटाएं",
    cart: "कार्ट", cartEmpty: "आपकी कार्ट खाली है", cartEmptyDesc: "संग्रह ब्राउज़ करें और पसंदीदा पीस जोड़ें।",
    cartTotal: "कुल", checkoutWhatsapp: "WhatsApp से चेकआउट", continueShopping: "खरीदारी जारी रखें",
    qty: "मात्रा", itemsInCart: "आइटम कार्ट में", clearCart: "कार्ट साफ़ करें",
    loved: "पसंद", loves: "पसंद करते हैं", itemLoved: "आपको यह पीस पसंद आई",
    filterAll: "सभी", sortBy: "क्रमबद्ध करें", sortNewest: "नवीनतम", sortPriceLow: "कीमत: कम से ज़्यादा", sortPriceHigh: "कीमत: ज़्यादा से कम", sortMostLoved: "सबसे ज़्यादा पसंद",
    noItemsFound: "कोई पीस नहीं मिली", searchItems: "पीस खोजें...",
  },
};